### ISSUE TITLE
Add further badges to README of Python client

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1051]
### Body

Add some more badges to the [README file](https://github.com/apache/streampipes/blob/dev/streampipes-client-python/README.md) of the Python client.
For example a badge for codecov, supported python versions, or [interrogate](https://interrogate.readthedocs.io/en/latest/#badge-options) etc.

### Mentoring
As this ticket is marked as good first issue: @bossenti is happy to provide help for getting started, just tag him if you want to start working on this issue and need some help.
We don't have an explizit set of badges in mind, familiarize yourself a bit with the setup of the Python client and come up with some creative ideas 🎨 

### Important ❗ 
**Do not create any account or similar in behalf of Apache StreamPipes (e.g. for codecov) unless you are part of the PMC!
If this is required in any kind, reach out to @dominikriemer, @tenthe or @bossenti.** 

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by nishith-p-shetty** [comment]
What badges. any Examples...?

**Comment by bossenti** [comment]
@nishith-p-shetty I am talking about the typical badges used for README files like on our main README but in this case specific for python
<img width="833" alt="Bildschirm­foto 2023-01-08 um 20 45 18" src="https://user-images.githubusercontent.com/50115603/211215760-552aeec2-ae6a-4898-b669-49397868bb31.png">

You can get some inspiration from well-known python libraries or browse a bit [here](https://naereen.github.io/badges/)
At least I would expect a codecov badge here

**Comment by dominikriemer** [comment]
Should we add the codecov badge to the main repo as well and enable codecov for the whole project?

**Comment by bossenti** [comment]
@dominikriemer thats a good idea
if possible I would create two badges then, one for StreamPipes itself and one for the python client

**Comment by bossenti** [comment]
Some interesting badges are only possible with having an actual PyPi deployment. 
Probably it's the best to wait with this issue until then.
