### ISSUE TITLE
Python MkDocs use old StreamPipes logo

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#1088]
### Description
MkDocs still use the old StreamPipes logo (See [1]). 
This should be replaced with the new logo.

### Mentoring

As this ticket is marked as good first issue: @bossenti or @tenthe are happy to provide help for getting started, just tag one of them if you want to start working on this issue and need some help.
This issue might be a good issue for people who want to get started contributing to StreamPipes.

[1] https://github.com/apache/streampipes/blob/dev/streampipes-client-python/mkdocs.yml

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by Pranjul2002** [comment]
hey, i am new to open source and i want to start my journey in open source project.
 I would like to work on this issue,can you guide me to this issue.

**Comment by dominikriemer** [comment]
Hi @Pranjul2002 and welcome!

The following steps would be needed:
1) The correct white logo can be found at https://github.com/apache/streampipes/blob/dev/ui/deployment/dev/img/logo-navigation.png
2) Fork the website project from https://github.com/apache/streampipes-website
3) In the website repo, replace the old logo with the new logo under https://github.com/apache/streampipes-website/tree/dev/website/img (sp-logo-white-right)
4) Create your first PR in StreamPipes ;-)

Please ask if you have any further questions!

**Comment by Pranjul2002** [comment]
so basically i have to replace logo under https://github.com/apache/streampipes-website/tree/dev/website/img with new one.

**Comment by parthsali** [comment]
Hey @bossenti, I think I can fix this issue. Can I start working on it now?

**Comment by bossenti** [comment]
@parthsali sure, that would be great 👍

**Comment by parthsali** [comment]
I changed the logo, but It is not visible as the background is also white. What should I do @bossenti?

![img](https://user-images.githubusercontent.com/108068631/212483379-b7dc1323-5dcf-466d-9dc3-3b731a6503fb.png)

**Comment by bossenti** [comment]
Then you replaced probably the wrong one ;) 
This one needs to be updated/replaced: https://github.com/apache/streampipes-website/blob/dev/website/img/sp-logo-white-right.png

**Comment by parthsali** [comment]
The correct logo is white, right? and the background color of the navbar is also white. That's why it is not visible.

**Comment by bossenti** [comment]
Yes, I understood the issue.
But you probably replaced the file `sp-logo-color.png` right?
This should stay as it is, because this is the right and current logo of StreamPipes in colors.
The only one that needs to updated is the white version of the logo (`sp-logo-white-right.png`).
The one at https://github.com/apache/streampipes-website/tree/dev/website/img  still uses the old icon.
The white version of the logo is used in the docs of our Python client as described above.

**Comment by parthsali** [comment]
My apologies, I just messed up  : (

**Comment by parthsali** [comment]
hey @bossenti, The PR has been sent and the old logo has been replaced with the new one. Please check if is it correct.
