### ISSUE TITLE
Extend StreamPipes API by a health-check endpoint

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1101]
### Body

Provide an additional endpoint to the StreamPipes API that just returns a `200` status code and some general information, e.g., the StreamPipes version running when the user is authenticated to access the API.

### Mentoring
As this ticket is marked as good first issue: @dominikriemer or @tenthe are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by deexidee** [comment]
Hi @dominikriemer @tenthe !
I'm new to open source and this issue seems to me as a good beginning point.
Could you please give me some hints on where to start?

**Comment by tenthe** [comment]
Hi @deexidee,
welcome to the StreamPipes project :)

As a first step, I would suggest that you start by setting up the development environment. 
You can find a description in [1]. 
Please let me know if you have any questions about the setup process. 

StreamPipes has two main types of services, the **service core** [2] which contains the backend of the application, and **extension services** [3]. I suggest that you first take a look at the REST API of the core service.
Here is a link to the module with all the REST endpoints [4]. You could add the endpoint described in this issue there.

Don't hesitate to write us if you have any questions.

[1] https://cwiki.apache.org/confluence/display/STREAMPIPES/Core
[2] https://github.com/apache/streampipes/tree/dev/streampipes-service-core
[3] https://github.com/apache/streampipes/tree/dev/streampipes-service-extensions
[4] https://github.com/apache/streampipes/tree/dev/streampipes-rest

**Comment by deexidee** [comment]
@tenthe @bossenti 
Thanks for the guidance.
I've checked a few classes at the REST API and it seems that the method `[getVersionInfo](https://github.com/apache/streampipes/blob/6a5b00d7bf82a92a5771d2f356b9f5f6f18b1266/streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/Version.java#L36)` in "Version" class implements the same functionality as the issue description.
Should I rename the method, add the same method with a different name to this class, or add it somewhere else?

**Comment by tenthe** [comment]
Hi @deexidee,
oh yes you are right. I think we can use the existing endpoint for the functionlality described in this issue.
@bossenti what do you think? My suggestion would be to close this issue.

Another issue in the REST API to get started with, is to remove some deprecated API endpoints from the REST interface.
I'd suggest to remove all the endpoints marked with `@Deprecated(since = "0.71.0", forRemoval = true)`.
The first step would be to create an issue for that. Then we should check if the API is no longer used in the UI
Finally we can remove the endpoints. 
I will be happy to assist you. You can provide a PR and we can discuss the details there.

**Comment by bossenti** [comment]
One point that we could do within this issue nevertheless is to ensure that the endpoint you've detected appears in our swagger doc
Apart from that, +1

**Comment by deexidee** [comment]
Ok, I'll check it and then start with deprecated endpoints.
Another question, what do I need to do to assign the issue to myself?

**Comment by deexidee** [comment]
Suppose I need a permission to push branches to the repo

**Comment by tenthe** [comment]
Hey, you need to make a fork of the repo and then provide a Pull Requst with the changes

**Comment by deexidee** [comment]
Sorry for missing for a while, had a busy week.
I made the PR, feel free to review :)

**Comment by tenthe** [comment]
Cool, thanks. I'll have a look at it.
