### ISSUE TITLE
Add GitHub wofklow that tags PR

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1104]
### Body

Implement a GitHub workflow that automatically assigns labels to PRs.
Fur this purpose consider to use the following GitHub action: https://github.com/actions/labeler

### ToDos:

- [x] provide config file to define labeling rules
- [x] implement GitHub workflow that runs for every created PR and assigns labels to it

### Metoring
As this ticket is marked as good first issue: one of @dominikriemer, @tenthe, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
It would be great if you discover our repository by yourself (this is a great oppurtinity to get to know the basic StreamPipes components) and come up with a proposal for labeling rules. But if you struggle with that we are happy to help you making a first draft.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by Harry262530** [comment]
Hello,
I would like to contribute in this issue

**Comment by bossenti** [comment]
Hi @Harry262530, awesome 🤩 
Do you need any help for getting started?

**Comment by bossenti** [comment]
Okay, the first step is to fork this repository to your own GitHub account.
Next, check out your own fork and create a branch which should ideally be named `1104-add-github-wofklow-that-tags-pr` (or similar).
Then you already can start with implementing the GitHub workflow.
You can find all our existing workflows in [`.github`](https://github.com/apache/streampipes/tree/dev/.github).

Once you have the workflow ready, you can create a PR in this repository and we will review you it 
Feel free to reach out in case you get stuck :)

**Comment by Harry262530** [comment]
sure
i'll try my best

**Comment by Harry262530** [comment]
I need a little Guidance,
 I have created a branch of  this repo and I have thoroughly gone through labeler repo and workflow of this repo, now I am stuck at how to start working with the workflow and including labels.

**Comment by bossenti** [comment]
Okay, so at first we want to have an additional workflow. So there is no need to integrate with the existing ones.
You can create a new file and call it e.g. `pr-labeling.yaml`.
This workflow should be executed when a PR is created.
Here you can follow the example of `labeler` pretty close: https://github.com/actions/labeler#create-workflow
The more difficult part is the configuration file. If you want to, you can take some time and familiarize your self with our existing labels and the codebase and come up with a proposal.
But you don't need to, you can also just provide the workflow itself and we will then come up with the configuration file.

Does this help you?

**Comment by bossenti** [comment]
This might be also of help: https://github.com/actions/labeler#create-workflow

**Comment by Harry262530** [comment]
I have created a pull request for the workflow and config file
can you please go through them
