### ISSUE TITLE
Build Github worfklow with OSV scanner

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1107]
### Body

Build a GitHub wofkflow that applies Google's [OSV scanner](https://github.com/google/osv-scanner) on a monthly(?) schedule on our repository.
This tool scans dependencies for vulnerabilities.
Open for discussion is how the output of the scan can be reported or displayed.

### Mentoring
As this ticket is marked as good first issue: one of @dominikriemer, @tenthe, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by Kshitiz-Mhto** [comment]
@bossenti could you review it ? i just gave it a try, am i on the right track?
![osv-scanner](https://user-images.githubusercontent.com/102871719/226101694-aac9e62a-9b61-420e-8fd8-c35f8ab8bc6e.png)

**Comment by Kshitiz-Mhto** [comment]
output:

![osv-op](https://user-images.githubusercontent.com/102871719/226101844-fbb71b5e-8e1a-4345-8613-a9acedf02151.png)

**Comment by bossenti** [comment]
PS: It's more convenient for us to review code snippets if you just open an WIP PR.
Screenshots are not ideal to share code, especially when the changes affect more than one file 🙂

**Comment by Kshitiz-Mhto** [comment]
Here, an example of implementation using `ghcr.io/google/osv-scanner:latest ` gh-action ie ,  https://github.com/Kshitiz-Mhto/EPL-data-board/actions/runs/4482600370/workflow

**Comment by Kshitiz-Mhto** [comment]
Demo using docker image `hcr.io/google/osv-scanner:latest` (https://github.com/Kshitiz-Mhto/EPL-data-board/actions/runs/4482978960/jobs/7881694486)

**Comment by bossenti** [comment]
Alright, then let's go with the docker image 🙂
