### ISSUE TITLE
Support output streams in functions

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#1133]
### Body

Add a feature to function definitions which allows to publish events back to StreamPipes.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by tenthe** [comment]
Hi @dominikriemer,
how will the workflow be for the data streams created by functions?
Do you already have an idea how we can integrate this into the e2e testing strategy?
Cheers,
Philipp

**Comment by dominikriemer** [comment]
Hi @tenthe, here is an example:
https://github.com/apache/streampipes-examples/blob/dev/streampipes-pipeline-elements-examples-processors-jvm/src/main/java/org/apache/streampipes/function/example/FunctionPublishExample.java

We can have some test functions that are integrated into the e2e tests or write some integration tests.
