### ISSUE TITLE
Upgrade third-party services

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#1157]
### Body

In our installers, we currently use some third-party services which are outdated:

* CouchDB (`3.3.1`)
* InfluxDB
* Consul

These should be upgraded to the latest version.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by bossenti** [comment]
Do you already have an impression on how many adaptions are required on our end?
Can we cover all three in one issue?
