### ISSUE TITLE
UI Semantik Type field is too small to see full term

### ISSUE THREAD

**Issue by flomickl** [apache/streampipes#1199]
I found another UI point 
If I want to add a semantic type in the adapters, the field is too small to see the full length.
Either to see the full length or just the last bit of it with the important vocabulary.

![Auswahl_040](https://user-images.githubusercontent.com/16739072/211374958-a14195d9-dc5f-4b77-a17e-64d544d60c3c.png)

_Originally posted by @flomickl in https://github.com/apache/streampipes/discussions/828#discussioncomment-4636384_

**Comment by abhishek423** [comment]
Hi Team, 

I am willing to work on this as my first issue, if it can be assigned to me?

My understanding with this is that:

**Issue**:
The dropdown text(semantic type term) is not fully understandable to the user while selecting in case of long term.

**Proposed Resolution**:
With respect to fix, if we can pop up a tooltip (with full term value) while hovering on dropdown value as per below image.
![image](https://user-images.githubusercontent.com/23099644/234473926-89a4cff2-a86e-47b0-baee-1f1d9cc5527c.png)


@bossenti , @flomickl , please guide me, if I'm missing anything on this or if any suggestion.

Thanks.
Abhishek

**Comment by bossenti** [comment]
Hey @abhishek423 👋

Appreciate your intention to help here. 
Yes, your summary is right. 
Your proposed solution looks already pretty good. 
Another idea that comes to my mind is to increase the width of the drop-down menu. Maybe you can give this a try as well?

**Comment by abhishek423** [comment]
Hi @bossenti,

Thanks for the feedback.

If the below image is fine as per the suggested increased dropdown width? Let me know if any more changes needed.

![image](https://user-images.githubusercontent.com/23099644/234648432-83a95ec9-3b9c-4f25-8f06-5a0e2bfb8fa0.png)

**Comment by bossenti** [comment]
Thanks a lot @abhishek423 
Looks great!
Looking forward to your contribution 🚀
