### ISSUE TITLE
Can't aggregate calculation results of the Math processing element

### ISSUE THREAD

**Issue by SvenO3** [apache/streampipes#1291]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

Processing Elements

### What happened?

When calculating a new field with the  `Math` processing element, you can only aggregate the calculation result with `First`, `Last`, `Mode` and `Count` in the Data Explorer, but you can't use `Mean`, `Min`, `Max` or `Sum`. 

### How to reproduce?

Create a pipeline, use a data source with two numerical fields and use the  `Math` processing element to calculate a new field:
![math_pipeline](https://user-images.githubusercontent.com/43231162/219004142-7d98ba94-6fd5-4946-a4fd-648ef20e289e.png)
When you agregate the calculation result with `First` every thing is fine:
![aggregated_first](https://user-images.githubusercontent.com/43231162/219004697-3faff523-e2ae-4a36-83ce-8d69e196c8de.png)
But if you try to show the `Mean` it does't work:
![aggregated_mean](https://user-images.githubusercontent.com/43231162/219005030-42ef202a-1801-4e04-b4b9-9ff33a3a89e8.png)

### Expected behavior

Maybe there's an error with the type of the calculation result.

### Are you willing to submit a PR?

None

**Comment by SteveYurongSu** [comment]
Hi @SvenO3 @bossenti , I'd like to try to work on this issue. Could you assign it to me, thanks! :D

**Comment by bossenti** [comment]
Awesome 🤩 
Already done

**Comment by SteveYurongSu** [comment]
> Hi @SvenO3 @bossenti , I'd like to try to work on this issue. Could you assign it to me, thanks! :D

I think I know where the problem is, but it might still take me some time to solve... So, you can assign it to me if there is no hurry 😃

**Comment by SteveYurongSu** [comment]
> Awesome 🤩 
> Already done 

Oh thanks!!! Will try my best to fix it.
