### ISSUE TITLE
Rename java module name `streampipes-extensions-management`

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#1293]
## Description
The module name in the `pom.xml` file in the `streampipes-extensions-management` module is set to **Semantic Event Processing Agents**. 
This should be renamed or the name should be removed.

## Mentoring

As this ticket is marked as good first issue: one of @dominikriemer or @tenthe are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by BudhirajaChinmay** [comment]
Hi @dominikriemer, Please assign this issue to me if no one has started yet.

**Comment by tenthe** [comment]
Hello @BudhirajaChinmay,
welcome to the project.
No one is working on it yet, so you can create a PR for the issue.
