### ISSUE TITLE
Filename too long under Windows when running pip install from dev repo

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#1360]
### Body

When running `pip install` with the command described in the README file of `streampipes-client-python` a `Filename too long` error appears as the whole StreamPipes repo is pulled which seems to have paths that are longer than the default maximum size allowed by Windows.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by bossenti** [comment]
Hi @dominikriemer,

I think this is a common issue for git on Windows.
For reference see: https://stackoverflow.com/a/22575737
Are you fine with this solution?
