### ISSUE TITLE
Convenient `columns` query parameter for data lake measure

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1374]
### Body

Currently, the python client expects a comma separated string when specifying the columns to be returned ( query parameter `columns`, see [here](https://github.com/apache/streampipes/blob/dev/streampipes-client-python/streampipes/endpoint/api/data_lake_measure.py#LL42)) for a data lake measure. This is quite inconvenient and should be replaced by the option to provide a list of strings which is then converted to a comma separated string for the actual query param. This transformation should be done with a [pydantic validator](https://docs.pydantic.dev/usage/validators/).

### Mentoring
As this issue is marked as good first issue: one of @SvenO3 , or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue is ideal for people that are interested in getting started with StreamPipes and making their first steps in our Python library.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by TheClerici** [comment]
Hi! I would love to get started on this project and help in this one

**Comment by bossenti** [comment]
Welcome to StreamPipes @TheClerici  🙌 
Great to hear!
Do you need nothing to get started?

**Comment by bossenti** [comment]
Alright, no worries!

**Comment by jjbiggins** [comment]
@bossenti I'm happy to take this.

**Comment by bossenti** [comment]
welcome at StreamPipes @jjbiggins, we really appreciate your interest to contribute here :) 

You can find some information about how to set up the development environment for StreamPipes Python after you cloned the repository:
https://streampipes.apache.org/docs/docs/python/latest/getting-started/developing/

If you want to test your code against a running StreamPipes instance, then the easiest way is to use the docker-compose deployment (https://streampipes.apache.org/docs/docs/try-installation.html#install-streampipes), use our quickstart example (https://streampipes.apache.org/docs/docs/python/latest/getting-started/quickstart/) to get you connected.

If there are any open questions from your end, feel free to raise them here

**Comment by jjbiggins** [comment]
Thanks. I'll dive into this

**Comment by jjbiggins** [comment]
Opened PR

**Comment by jjbiggins** [comment]
Messed up and accidentially closed linked issue #1653. This commit should be up-to-date and include discussed changes. Created new pull request. My bad about the inconvenience.

**Comment by bossenti** [comment]
> Messed up and accidentially closed linked issue #1653. This commit should be up-to-date and include discussed changes. Created new pull request. My bad about the inconvenience.

No worries!
