### ISSUE TITLE
Google Summer of Code: OPC-UA Browser for Apache StreamPipes

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#1390]
### *****Apache StreamPipes*****

Apache StreamPipes (incubating) is a self-service (Industrial) IoT toolbox to enable non-technical users to connect, analyze and explore IoT data streams. StreamPipes offers several modules including StreamPipes Connect to easily connect data from industrial IoT sources, the Pipeline Editor to quickly create processing pipelines and several visualization modules for live and historic data exploration. Under the hood, StreamPipes utilizes an event-driven microservice paradigm of standalone, so-called analytics microservices making the system easy to extend for individual needs.

### *****Background*****

StreamPipes is grown significantly throughout recent years. We were able to introduce a lot of new features and attracted both users and contributors. Putting the cherry on the cake, we were graduated as an Apache top level project in December 2022. We will of course continue developing new features and never rest to make StreamPipes even more amazing. 

StreamPipes really shines when connecting Industrial IoT data. Such data sources typically originate from machine controllers, called PLCs (e.g., Siemens S7). But there are also new protocols such as OPC-UA which allow to browse available data within the controller. Our goal is to make connectivity of industrial data sources a matter of minutes.

Currently, data sources can be connected using the built-in module `StreamPipes Connect` from the UI. We provide a set of adapters for popular protocols that can be customized, e.g., connection details can be added. 

To make it even easier to connect industrial data sources with StreamPipes, we plan to add an OPC-UA browser. This will be part of the entry page of StreamPipes connect and should allow users to enter connection details of an existing OPC-UA server. Afterwards, a new view in the UI shows available data nodes from the server, their status and current value. Users should be able to select values that should be part of a new adapter. Afterwards, a new adapter can be created by reusing the current workflow to create an OPC-UA data source.

This is a really cool project for participants interested in full-stack development who would like to get a deeper understanding of industrial IoT protocols. Have fun! 

### *****Tasks*****

- [ ] get familiar with the OPC-UA protocol
- [ ] develop mockups which demonstrate the user workflow
- [ ] develop a data model for discovering data from OPC-UA
- [ ] create the backend business logic for the OPC-UA browser 
- [ ] create the frontend views to asynchronously browse data and to create a new adapter
- [ ] write Junit, Component and E2E tests
- [ ] what ever comes in your mind 💡 further ideas are always welcome

### *****Relevant Skills*****

- interest in Industrial IoT and procotols such as OPC-UA
- Java development skills
- Angular/Typescript development skills

Anyways, the most important relevant skill is motivation and readiness to learn during the project!

### *****Learning Material*****

- [StreamPipes documentation](https://streampipes.apache.org/docs/docs/user-guide-introduction.html)
- [Our current OPC-UA adapter](https://github.com/apache/streampipes/tree/dev/streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/opcua)
- [Eclipse Milo, which we currently use for OPC-UA connectivity](https://github.com/eclipse/milo)
- [Apache PLC4X, which has an API for browsing](https://plc4x.apache.org/)

*****Mentor*****
 - Dominik Riemer (riemer[at]apache.org).

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by purplesmurf45** [comment]
Hello @dominikriemer,
I’d love to learn more and contribute to this project! I have subscribed to the dev mailing list. Could you let me know how to proceed hereafter?

**Comment by dominikriemer** [comment]
Hi @purplesmurf45, great that you are interested in this project!
I suggest you try to get familiar with the project, set it up and get a rough overview of the current approach to create adapters.

Some guidelines on writing up a proposal can be found here https://community.apache.org/gsoc.html.

If you have any questions, feel free to ask on the mailing list!

**Comment by Anurag-modgil** [comment]
hi @dominikriemer and @bossenti 

I hope this message finds you well. I wanted to reach out and express my interest in contributing to the OPC UA project. Recently, I have been focusing on getting familiar with OPC UA and I feel confident in my understanding of it.

I am excited about the potential of this project and I would be thrilled to have the opportunity to contribute my skills and knowledge to help it grow. Please let me know if there is anything specific you think I could contribute or any areas where help is needed.

Thank you for all of the hard work you and the team have already put into this project. I look forward to the possibility of working with you.

**Comment by bossenti** [comment]
Hi @Anurag-modgil 
welcome at StreamPipes 🎉 
Great that you are interested in our GSOC challenge.
With respect to contributions, are talking about making contributions beside the GSOC?
In this case you may have a look on the following issues:
- https://github.com/apache/streampipes/issues/1113 might be valuable to mark yourself familiar with the functionality of our adapters in general
- In case you want to make yourself familiar with our current OPC-UA setup there are two options: 1) https://github.com/apache/streampipes/issues/889 and 2) add caching for OPC-UA adapters (here we do not have an issue yet, but an existing discussion https://github.com/apache/streampipes/discussions/888#discussioncomment-4483352)
- Another issue for discovering our adapters: https://github.com/apache/streampipes/issues/530
- Here are two great issues to make yourself familiar with our pipeline elements: https://github.com/apache/streampipes/issues/1315 & https://github.com/apache/streampipes/issues/529

In case you are interested in one of them, just leave a comment there. This allows me to assign you.

If your question targeted more towards the GSOC process, you might have a look here: https://summerofcode.withgoogle.com/how-it-works

**Comment by purplesmurf45** [comment]
Hi @bossenti, @dominikriemer 
I was successfully able to set up the project locally! Additionally, I went over the current documentation on creating adapters. Can I work on #1113  if it isn’t assigned already? This will really help me familiarise myself with the adapters. I’m also open to working on any other issues you’d recommend 😁

**Comment by bossenti** [comment]
@purplesmurf45 that's great 🎉 
#1113 is a great one to start with
If you leave a comment there, I can assign you
We are happy to help you, in case there are any questions 🙂

**Comment by bossenti** [comment]
@purplesmurf45 @Anurag-modgil if you are still interested in working on this topic as part of this year's GSOC, I would like to kindly remind you to write your project proposal and submit it by 2023/04/04 (https://summerofcode.withgoogle.com/programs/2023).
Here is more information on how to write a proposal: https://google.github.io/gsocguides/student/writing-a-proposal
In case there any open questions, feel free to reach out
Good luck 🙂

**Comment by Anurag-modgil** [comment]
hi @bossenti  i am very willing to contribute through gsoc and lear new things can you suggest me some proposal any template

**Comment by bossenti** [comment]
@Anurag-modgil I think in terms of expected content and structure, Google's documentation describes it pretty well
In terms of the technical aspects you can get some inspiration from the issue's description

**Comment by akhileshappala** [comment]
Hi @dominikriemer , @bossenti 
I am sorry that I am late to the race, I am working on the other project.

I found out about this project today, It is very interesting and  I have a previous experience with OPC-UA in node-red. 
I have implemented the OPC-UA server for the communication between the 2 legacy instruments like a subscribe and publishing communicator.

As I don't have much time. I will be coming up with a good proposal in a couple of days.
Can you please let me know what I need to do, to prioritize my proposal?

**Comment by bossenti** [comment]
Hi @akhileshappala 

Great that you are interested in this GSOC challenge 🤩
Your experiences sound pretty suitable 
We would really appreciate receiving to receive a proposal from you 
Honestly, I did't really get how we can support you 
If there are any unclear aspects we are happy to sort them out 🙂

**Comment by akhileshappala** [comment]
Hi @bossenti 
Thank you.
As I mentioned I will.be coming up with my proposal for the project.
As I have very less time to get it reviewed and do the changes. Once I complete the draft proposal, I will work on the first good bugs.

**Comment by bossenti** [comment]
Sounds good! 
We will for sure find time to give you feedback as fast as possible 🙂

**Comment by dominikriemer** [comment]
@purplesmurf45 @akhileshappala @Anurag-modgil and all others who are interested in this challenge:
Since the deadline is approaching, if you have any questions related to the proposal, feel free to ask in this thread!

**Comment by Anurag-modgil** [comment]
hi @bossenti 
Would you be able to provide guidance on how I can best include the given tasks in my proposal?

**Comment by bossenti** [comment]
Hi @Anurag-modgil 
In general your proposal should describe both what and why you want to achieve during GSOC. This can include a list of tasks like in the ticket's description but beside that should also go more into detail.
Hope this helps ✌️

**Comment by bossenti** [comment]
Hi @Anurag-modgil 
In general your proposal should describe both what and why you want to achieve during GSOC. This can include a list of tasks like in the ticket's description but beside that should also go more into detail.
Hope this helps ✌️

**Comment by bossenti** [comment]
@akhileshappala we either communicate via the mailing list or via GitHub discussions. We have a channel in the ASF's Slack space too, but only use it very rarely since it is restricted to ASF committers

**Comment by bossenti** [comment]
In general you are free to choose, but if you have general or basic technical questions, GitHub discussions is the way to go

**Comment by akhileshappala** [comment]
Cool, Thanks for the information. 
Can you please share your email id,  to share my draft proposal?

**Comment by bossenti** [comment]
Mine is bossenti@apache.org 🙂 
By I probably won't be able to review it before Sunday

**Comment by purplesmurf45** [comment]
Hi @dominikriemer, @bossenti can I share my proposal for review to your respective emails by this Sunday? I am really sorry about the short notice...

**Comment by bossenti** [comment]
Sure, feel free to do so (see E-mail addresses above)
Ideally, you already add the proposal to the GSOC platform, that's the easiest way to access for us 🙂

**Comment by purplesmurf45** [comment]
@dominikriemer @bossenti I am writing to inform you that I will not apply for GSoC 2023. This is due to a lack of time to write a thorough proposal. I request you to continue guiding me as I contribute to Streampipes. I plan on applying for GSoC next year and would like to further familiarize myself with the codebase, functionalities and tech stack in the meantime.

**Comment by bossenti** [comment]
@purplesmurf45 thanks for getting back to us
We are glad to hear that you are willing to continue contributing to StreamPipes
We really appreciate this, contribution in any form is always welcome (independent from GSCO 🙂) 🚀

**Comment by bossenti** [comment]
@Anurag-modgil please be aware that this issue is considered as a `large` project, whereas you assess it as `medium` in your proposal

**Comment by Anurag-modgil** [comment]
yes i am aware of that , thanks.

**Comment by bossenti** [comment]
Solved by https://github.com/apache/streampipes/pull/1675
