### ISSUE TITLE
Enable search for Python docs

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1405]
### Body

Our [Python docs ](https://github.com/apache/streampipes/tree/dev/streampipes-client-python/docs) are built with Mkdcocs.
To improve the user experience we would like to add support for a search bar that allows to search the documentation.
Fortunately, Mkdocs provides a plugin for this: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#a-single-language

### Mentoring
As this issue is marked as good first issue: one of @SvenO3 , or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue is ideal for people that are interested in getting started with StreamPipes and making their first steps in our Python library.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by amaan-n-j** [comment]
Hi @bossenti I would like to work on this issue.

**Comment by bossenti** [comment]
Welcome @ StreamPipes @amaan-n-j 🙌
In case you have any questions feel free to reach out

**Comment by Anurag-modgil** [comment]
hi @bossenti please help me out 
where i can find mkdocs.yml file to add plugin

**Comment by bossenti** [comment]
@Anurag-modgil 
You can find the mkdocs config here: https://github.com/apache/streampipes/blob/dev/streampipes-client-python/mkdocs.yml
But we already have an open PR for this issue(see #1408)
Nonetheless, thank you for your willingness to contribute 🙏🏼
