### ISSUE TITLE
TaskDuration

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1435]

**Comment by bossenti** [comment]
@liuxiaocs7 did you accidentally assign yourself or are you interested in contributing here?

**Comment by liuxiaocs7** [comment]
Hi, @bossenti, this issue may be resolved by #1613, and i think it can be closed, and sorry I accidentally clicked the wrong button yesterday

**Comment by bossenti** [comment]
Indeed it is, thanks for pointing!
No worries, I'm just trying to keep up with @dominikriemer's speed
