### ISSUE TITLE
Extend Python docs with dark mode

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1442]
### Body

Our [Python docs](https://github.com/apache/streampipes/tree/dev/streampipes-client-python/docs) are built using [mkdocs-material](https://squidfunk.github.io/mkdocs-material/).
This allows to easily configure a dark mode as described here: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=dark+mode#color-palette-toggle
This issue is about configuring the dark mode for our Python docs via the [mkdocs.yml](https://github.com/apache/streampipes/blob/dev/streampipes-client-python/mkdocs.yml). Please pay some attention on the selected primary and accent color for the dark theme.

### Monitoring
As this issue is marked as good first issue: one of @SvenO3 , or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue is ideal for people that are interested in getting started with StreamPipes, and want to get a little hands-on to our Python library.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by dev-DTECH** [comment]
Hey, I want to work on this issue.

**Comment by dev-DTECH** [comment]
Thank you @tenthe for assigning this issue to me.

**Comment by dev-DTECH** [comment]
What about the logo?
> its getting a bit unreadable due to dark colors

![image](https://user-images.githubusercontent.com/55497045/227449704-2a505b2a-13f6-4a18-a4d0-9e9c9fad3104.png)

**Comment by tenthe** [comment]
Yes, you are right it is quite unreadable. @bossenti is it possible to use the white logo for dark mode?

**Comment by bossenti** [comment]
For images within markdown files there is a functionality to distinguish between dark and light mode:https://squidfunk.github.io/mkdocs-material/reference/images/#light-and-dark-mode
However, I think this does not apply for the general logo (appearing in the top left corner)

**Comment by dev-DTECH** [comment]
# So I edited the logo to improve the readability with dark mode.
> Is it ok to use this logo?

## Light Mode -
![image](https://user-images.githubusercontent.com/55497045/227602679-e331bed8-853b-45ec-adbe-6953b94e5854.png)

## Dark Mode -
![image](https://user-images.githubusercontent.com/55497045/227603054-1a88d56a-90df-4485-ab22-33ad3e39945b.png)

**Comment by dev-DTECH** [comment]
@bossenti is it legal to use this edited logo? like no license issue etc...

**Comment by dev-DTECH** [comment]
Ok sure

**Comment by dev-DTECH** [comment]
@tenthe What about the python logo its not there in the all white logo.
> Should I add it?
![image](https://user-images.githubusercontent.com/55497045/227850080-21fe3c4b-f7be-4521-9418-a77e84ee6f6c.png)

**Comment by dev-DTECH** [comment]
ok got it @tenthe

**Comment by dev-DTECH** [comment]
@tenthe I have committed with the white logo, please accept the PR.
> It looks like this now
![image](https://user-images.githubusercontent.com/55497045/228045988-5cf7afe7-6127-4a8a-9c8a-7538b3b3f79d.png)

**Comment by bossenti** [comment]
completed with #1454
