### ISSUE TITLE
standalone dashborad empty

### ISSUE THREAD

**Issue by obermeier** [apache/streampipes#1547]
### Apache StreamPipes version

0.91.0

### Affected StreamPipes components

UI

### What happened?

When navigating to /#/standalone/sp:dashboardmodel:... the page contains the StreamPipes logo only.

The a javascript error tells that
   ERROR TypeError: this.allMeasurements is undefined

### How to reproduce?

Create a dashbord and cklick on the standalone button.

### Are you willing to submit a PR?

None

**Comment by tenthe** [comment]
@obermeier thanks a lot for reporting the bug.
If anyone is interested it would be a good first issue to reproduce the behavior in an e2e test

**Comment by bossenti** [comment]
As proposed by @tenthe, the first step here is to reproduce the bug by implementing an E2E testcase for it.
Once this is done, we can then try to fix the behavior and end up with a green test case.

**Comment by obermeier** [comment]
@dominikriemer thank you for this fixing this.
