### ISSUE TITLE
Rename File-Download Files

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#159]
Currently there is a static file name containing a space character is created. Change this to a more meaningful name (e.g. date_indexname) with no special characters

Imported from Jira [STREAMPIPES-47](https://issues.apache.org/jira/browse/STREAMPIPES-47). Original Jira may contain additional context.
Reported by: zehnder.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in "open" status due to migration from JIRA.
