### ISSUE TITLE
Rename the interface `AdapterInterface` to `IAdapter` in the `remove-set-adapter` branch

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#1590]
### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by dominikriemer** [comment]
What about naming this `StreamPipesAdapter` so that it is consistent to the existing `StreamPipesDataProcessor` and `StreamPipesDataSink?

**Comment by bossenti** [comment]
+1 for @dominikriemer's suggestion
This is already adapted accordingly in #1290
