### ISSUE TITLE
Connect IO-Link Sensor Data into StreamPipes

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#1592]
### Summary

The IO-Link Master (AL1350) has an IoT interface to transmit sensor data over MQTT. As a user, I would like to have an adapter that connects IO-Link sensor data into StreamPipes.

### Details

The IO-Link Master can be configured to transmit JSON events to an MQTT broker. These JSON events contain meta-information and the values of the sensors connected to the port. However, the sensor values are encoded and require decoding for each sensor type.

The challenge we need to address is that an IO-Link Master can have different sensor types connected, but in StreamPipes, a fixed event schema is required for each data stream.

### Proposed Solution

To tackle this challenge, I suggest the following solution:

- **User Input:**
  - MQTT configuration: Allow users to configure the MQTT connection settings.
  - Select IO Link Ports: Enable users to select the IO Link ports they want to integrate with StreamPipes.
  - Select sensor type: Provide an option for users to select the sensor type connected to each port.

- **Output Schema:**
  - The output schema should be dependent on the selected sensor type. Each sensor type may have a different event schema in StreamPipes.

### Additional Information

There are multiple options available for mapping the MQTT event to the StreamPipes event. The suggested solution provides flexibility to users, allowing them to configure the MQTT settings and the sensor type.

By implementing this adapter, users will be able to seamlessly integrate IO-Link sensor data into StreamPipes, providing a unified and consistent event schema for analysis and processing.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by bossenti** [comment]
Completed by https://github.com/apache/streampipes/pull/1647
