### ISSUE TITLE
apachestreampipes/sources-vehicle-simulator:0.92.0-SNAPSHOT not found

### ISSUE THREAD

**Issue by loststar** [apache/streampipes#1597]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

Processing Elements

### What happened?

Similar as #778 
When attempting to run `docker-compose -f docker-compose.full.yml up -d`, I received the following error message:
```
 - sources-vehicle-simulator Error                                                                                 3.2s
Error response from daemon: manifest for apachestreampipes/sources-vehicle-simulator:0.92.0-SNAPSHOT not found: manifest unknown: manifest unknown
```
After further investigation on [apachestreampipes/sources-vehicle-simulator Tags | Docker Hub](https://hub.docker.com/r/apachestreampipes/sources-vehicle-simulator/tags), it appears that the latest available version is 0.69.0.

### How to reproduce?

Run `docker-compose -f docker-compose.full.yml up -d`

### Expected behavior

Launch as normal

### Additional technical information

```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:36:18 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.3 (96739)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by bossenti** [comment]
thanks a lot for reporting @loststar 🙏🏼 
We really appreciate your interest to contribute here.
Do you need any help to get started?

**Comment by loststar** [comment]
> thanks a lot for reporting @loststar 🙏🏼 We really appreciate your interest to contribute here. Do you need any help to get started?

Hi @bossenti, thank you for reaching out. Yes, I would appreciate some help. 🙏🏼
I think the root cause of the issue may be that `sources-vehicle-simulator` is not included in `streampipes/.github/workflows/build.yml`. As I noticed, the source code of this image is continually updated. So I assume adding this task to `build.yml` like [Task: Build and Push Docker Image sources-watertank-simulator](https://github.com/apache/streampipes/blob/d072af709b90b67e3c4f3485c85160731731307b/.github/workflows/build.yml#L135) can solve the problem.
Do you and have any concern about this? @bossenti @tenthe

**Comment by bossenti** [comment]
I'm not entirely sure here if `sources-vehicle-simulator` should still be part of the full deployment or if it was not properly removed 🤔
@dominikriemer @tenthe what are your thoughts here?

**Comment by tenthe** [comment]
Hello @loststar,
thank you very much.
You are right, it seems that the Docker image is not currently built.
I think we need to decide if we want to include this container in the full release or not.
My suggestion would be that we remove it for future releases, but as long as it is part of `docker-compose.ym`, we should provide a container.
What do you think about this?

**Comment by loststar** [comment]
Hi, @tenthe, I agree with you. It is a good idea to remove it before deciding if it is necessary.

**Comment by loststar** [comment]
Hi @bossenti and @tenthe, it looks like there aren't any more opinions, so I went ahead and submitted a PR based on our earlier discussion.

**Comment by bossenti** [comment]
@loststar awesome, thanks a lot!
