### ISSUE TITLE
Sink: HDFS

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#160]
## Description

Create a sink to store events into HDFS.
## Input Requirements
 * None

## Configurations
 * Host / Port
 * Folder Route
 * User / Password (optional)
 * Parameter for Buckets 

 

Imported from Jira [STREAMPIPES-49](https://issues.apache.org/jira/browse/STREAMPIPES-49). Original Jira may contain additional context.
Reported by: zehnder.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
