### ISSUE TITLE
Consider domain property for live preview

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#161]
In the live preview after starting an adapter, images and timestamps should be displayed in a human readable way.

Imported from Jira [STREAMPIPES-76](https://issues.apache.org/jira/browse/STREAMPIPES-76). Original Jira may contain additional context.
Reported by: zehnder.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
