### ISSUE TITLE
Add processor to filter for numerical and text values

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#162]
Currently, there are Numerical Filter and Text Filter. If a user wants to apply both, i.e. filter a field for a given string AND subsequently filter a numeric field based on a given threshold, these two PE's need to be concatenated to achieve this goal. In order to improve this common scenario there should be a new processor "Numerical Text Filter" to allow doing this in one step.

Imported from Jira [STREAMPIPES-72](https://issues.apache.org/jira/browse/STREAMPIPES-72). Original Jira may contain additional context.
Reported by: wiener.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
