### ISSUE TITLE
Processor: Merge two data streams by timestamp

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#163]
A user can use this processor to merge two data streams by their timestamp.

The processor should be implemented in Java to also run on edge devices.

Imported from Jira [STREAMPIPES-59](https://issues.apache.org/jira/browse/STREAMPIPES-59). Original Jira may contain additional context.
Reported by: zehnder.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
