### ISSUE TITLE
Support for multiple properties

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#164]
According to dev Email: "[Add support for multiple properties in PLC4X S7 Adapter](https://lists.apache.org/thread.html/38a7621c664ce80ddb932a8b6c21fb623a2f7f771f7a3443fc03cfe4%40%3Cdev.streampipes.apache.org%3E)"

Imported from Jira [STREAMPIPES-22](https://issues.apache.org/jira/browse/STREAMPIPES-22). Original Jira may contain additional context.
Reported by: tex.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
