### ISSUE TITLE
Move OPC-UA processor and sink into a single module

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#1648]
### Body

Merge the OPC-UA processor and the OPC-UA data sink into a new module `streampipes-connectors-opcua` to facilitate code reuse.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by bossenti** [comment]
great @dominikriemer!
I've added this task directly in my OPC UA action plan: https://github.com/apache/streampipes/discussions/1650

Should we include the description in the README mentioned there also in this issue or would you rather like to have a dedicated one?

**Comment by dominikriemer** [comment]
Should we create the README once we've refactored the adapter to share settings between the adapter and sink? I guess some configs might change until then...

**Comment by bossenti** [comment]
Sounds good 👍
