### ISSUE TITLE
Extract utils class for mqtt related configurations

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#165]
We have multiple adapters that connect to a MQTT broker. Therefore, they need the same configuration parameters.

To avoid having to implement these for every adapter we need a Utils class which encapsulates the configuration. 

 

Imported from Jira [STREAMPIPES-69](https://issues.apache.org/jira/browse/STREAMPIPES-69). Original Jira may contain additional context.
Reported by: zehnder.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
