### ISSUE TITLE
Exception in adpaters when the date format is incorect

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#166]
When a user marks a property as a timestamp, there is the possibility to provide a regex to convert the timestamp represented as a String into the internal representation of a UNIX timestamp in milliseconds. As long as the date in the events is formatted according to the regex this works properly. When there is an error in the data an exception is thrown and the adapter stops producing data. In this case the adapter should ignore the event instead and continue with the next event.

Imported from Jira [STREAMPIPES-57](https://issues.apache.org/jira/browse/STREAMPIPES-57). Original Jira may contain additional context.
Reported by: zehnder.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
