### ISSUE TITLE
Use internal file service in file adapters

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#167]
As described in the thread: Re: STREAMPIPES-75: Extend data lake sink to store images on the mailing list. The uploaded files of the file stream and file set adapter should not be stored in the local container, instead they should be stored in the centralized file service..

 

 

 

Imported from Jira [STREAMPIPES-80](https://issues.apache.org/jira/browse/STREAMPIPES-80). Original Jira may contain additional context.
Reported by: zehnder.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
