### ISSUE TITLE
Confluence wiki for StreamPipes

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#168]
Ask infra to setup the new Confluence wiki for StreamPipes targeted at contributors.

Imported from Jira [STREAMPIPES-21](https://issues.apache.org/jira/browse/STREAMPIPES-21). Original Jira may contain additional context.
Reported by: riemer.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
