### ISSUE TITLE
Refactor project namespace from org.streampipes to org.apache.streampipes

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#169]
Imported from Jira [STREAMPIPES-1](https://issues.apache.org/jira/browse/STREAMPIPES-1). Original Jira may contain additional context.
Reported by: riemer.

**Comment by dominikriemer** [comment]
The following subtask(s) are associated with this issue: #170, #171, #172

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
