### ISSUE TITLE
Support array types for OPC UA

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#1693]
Currently, the OPC UA adapter lacks support for arrays. OPC UA allows for the representation of data using basic data types as well as arrays. However, the current implementation of the adapter does not handle arrays properly in the events.

Details can be found in this discussion:
_Originally posted by @curichan in https://github.com/apache/streampipes/discussions/1650#discussioncomment-6170814_

**Comment by bossenti** [comment]
duplicate of #1980

**Comment by bossenti** [comment]
Issue still persists, see #2736
