### ISSUE TITLE
Error when using the `TimestampTranformationRule` in the file `FileReplayAdapter`

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#1708]
## Description
When a user selectes the `FileReplayAdapter` with the configuration `Use current time: true` or `Replay Speed: Keep original time` and applies a `Timestamp conversion` e.g. "2023-06-18 01:20:00" -> "yyyy-MM-dd HH:mm:ss" the following errors occur:

```
ERROR 34003 --- [pool-5-thread-1] o.a.s.c.i.p.stream.FileReplayAdapter : The timestamp field is not a unix timestamp in ms. Value: 2023-06-18 01:20:00
...
ERROR 34003 --- [pool-5-thread-1] e.m.c.a.p.t.v.TimestampTranformationRule : java.text.ParseException: Unparseable date: "1687325253093"
```

## Problem
The problem is that the the timestamp conversion from `String` to `Long` happens in the preprocessing rules of the adapter which are executed after the event is processed in the adapter.
In this case however the adapter already requires the timestamp value, because it is needed to publish the events in the correct frequency.

## How to reproduce
Use the following csv and create a File Stream Adapter.
```
timestamp,value
"2023-06-18 01:20:00",1.1
```

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by bossenti** [comment]
Fixed in https://github.com/apache/streampipes/pull/2559
