### ISSUE TITLE
Fix Docker repo URLs in installer CLI

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#173]
The env file of the CLI module of the installer links to some internal repos and need to be changed to a public Docker registry.

Imported from Jira [STREAMPIPES-29](https://issues.apache.org/jira/browse/STREAMPIPES-29). Original Jira may contain additional context.
Reported by: riemer.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
