### ISSUE TITLE
Deploy snapshots to Docker Hub

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#174]
Snapshots of the backend and pipeline element containers should be published to Docker Hub to ease development of StreamPipes

Imported from Jira [STREAMPIPES-10](https://issues.apache.org/jira/browse/STREAMPIPES-10). Original Jira may contain additional context.
Reported by: riemer.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
