### ISSUE TITLE
Extend supported data types for PLC4X S7 adapter

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#1742]
### Body

Currently only a limited number of data types are supported for the `PLC4X S7` adapter. This should be extended to support all data types that PLC4X offers.

### Mentoring
As this issue is marked as good first issue: one of @dominikriemer, @tenthe, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue is ideal for people that are interested in getting started with StreamPipes and ideally (but necessarily) have some experience with PLC4X.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by bossenti** [comment]
Is this still applicable even with our generic PLC4X adapters?

**Comment by tenthe** [comment]
I'll close this, since the generic PLC4X adpaters should support it.
