### ISSUE TITLE
Remove dependency to kafka-rest

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#176]
Kafka-rest is licensed under the Confluent Community license. Although not being used in the code directly, Kafka-rest ist currently required to get live data in the data stream preview. We need to find another way to show real-time previews.

Imported from Jira [STREAMPIPES-9](https://issues.apache.org/jira/browse/STREAMPIPES-9). Original Jira may contain additional context.
Reported by: riemer.

**Comment by bossenti** [comment]
Closing the issue as it is inadvertently in `open` status due to migration from JIRA.
