### ISSUE TITLE
The dashboard fails to load the element whose name contiains '/'

### ISSUE THREAD

**Issue by RobertIndie** [apache/streampipes#1769]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

Backend

### What happened?

The dashboard fails to load the element name contiains '/'

### How to reproduce?

- Creating a pipeline that contains a data lake named 'test/001'
- Create a dashboard and add a widget for the data lake
- The dashboard couldn't find the widget
<img width="859" alt="image" src="https://github.com/apache/streampipes/assets/16974619/569e5a86-9ccf-44a7-9b6d-df5233f7411d">

### Expected behavior

The dashboard could find the widget and display.

### Additional technical information

The root cause is that the URL is corrupted with '/'. Here is the request URL for this widget:
```
http://localhost:80/streampipes-backend/api/v3/datalake/pipelines/1cbeb7f2e1da494a9b9f45e36f63e513/test/001
```

We need to use the escape character here. Or reject the use of the name containing '/' when creating the element.

### Are you willing to submit a PR?

None

**Comment by dominikriemer** [comment]
@RobertIndie good catch!
I added a method to replace forbidden characters with an underscore, similar as we are rewriting fields which contain reserved keywords.
(I first tried to configure Tomcat to allow URL-encoded slashs, but couldn't manage to get the configuration property working, so I went for this solution.)
