### ISSUE TITLE
New Processor: Datetime from String

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1865]
### Description
A user should have the ability parse datetime values from string values in a pipeline. Therefore, a new processor is required that provides the functionality to convert a string value to a datetime value based on a given string format.

### Example Configuration
`DatetimeFormat` : A format string that describes the format of the datetime string

The datetime format should be configurable with a conveniant UI dialog, ideally similar to the our [Notification sink](https://github.com/apache/streampipes/blob/dev/streampipes-extensions/streampipes-sinks-internal-jvm/src/main/java/org/apache/streampipes/sinks/internal/jvm/notification/NotificationProducer.java):
![image](https://github.com/apache/streampipes/assets/50115603/911bd52f-d285-4b26-a20f-f7bfa405a049)

### Additional Functionality
If you have any other ideas for the functionality of this new processor, please feel free to add them here.

### Mentoring
As this issue is marked as good first issue: one of @dominikriemer, @tenthe, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue is ideal for people that are interested in getting started with StreamPipes and its SDK.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by dshunter107** [comment]
Hello @tenthe , I am interested in working on this problem, but I am quite new to the GitHub community. Would you be able to point me in the direction of which files/packages would be of interest to me. I'm still getting used to wading through large projects. 

Also, the description makes this seem like all I would need to do is implement some simple function like a ``LocalDate.parse("2023-18-05"); ``. Is this understanding correct, or would it need to be more involved.

**Comment by bossenti** [comment]
Hey @dshunter107,

thanks for your interest in contributing here 🙏🏼 
Don't worry, we are happy to assist you and guide you through your first steps on GitHub.

One important thing is the git flow for open source projects: https://www.asmeurer.com/git-workflow/
Please read through this to know how you can open a PR in our repository.

Since this issue involves introducing a new pipeline element, the following tutorial might be relevant for you: https://streampipes.apache.org/docs/extend-tutorial-data-processors
There might be some parts that are not completely up to date, we already have this on our radar. But if you face any issues, we are ready to help 🙂 

Since you asked, where to place the new processing element in our repo, I'd recommend you choose `streampipes-processors-transformation-jvm`: https://github.com/apache/streampipes/blob/eccb29ff437ea5c560d16bbf86e95e7f1011502f/streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/processor

Yes, that's probably the only thing we need 🙂 When writing this issue I thought way too complex, so I really liked your proposal.
The only aspect we need to pay attention to is the target time zone. Your snippet would just use the timezone of the JVM where the processor is running, right? This might not always be the appropriate one
