### ISSUE TITLE
Connect: Order measurement units by name

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#1875]
### Body

In StreamPipes connect's schema editor, users can assign a measurement unit to a field. The list of measurement unit is currently unordered, making it hard for users to find an appropriate unit.
The list should be sorted by name.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by bossenti** [comment]
Completed in https://github.com/apache/streampipes/pull/2018

**Comment by bossenti** [comment]
is fixed in #1960
