### ISSUE TITLE
Implement unit tests for pipeline element ‘ComposeProcesor‘

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1892]
This issue is about implementing unit tests for our pipeline element [ComposeProcessor](https://github.com/apache/streampipes/blob/752289c6acfc8fa10398c920d678c5c02143ed5c/streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/processor/compose).
An example of how to write unit tests for pipeline elements can be found [here](https://github.com/apache/streampipes/tree/ca4e0c2d44c1a713caaee3e9c1bff46096f41c53/streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor).

### Mentoring
As this issue is marked as a good first issue and for the `hacktoberfest` event: one of @dominikriemer, @tenthe, @RobertIndie, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.

**Comment by abhishek423** [comment]
Hi @bossenti ,  I would like to contribute on this. Could you please help in assigning this to me?
