### ISSUE TITLE
Implement unit tests for pipeline element 'SwingingDoorTrendingFilterProcessor'

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1901]
This issue is about implementing unit tests for our pipeline element [SwingingDoorTrendingFilterProcessor](https://github.com/apache/streampipes/blob/752289c6acfc8fa10398c920d678c5c02143ed5c/streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/processor/sdt).
An example of how to write unit tests for pipeline elements can be found [here](https://github.com/apache/streampipes/tree/ca4e0c2d44c1a713caaee3e9c1bff46096f41c53/streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor).

### Mentoring
As this issue is marked as a good first issue and for the `hacktoberfest` event: one of @dominikriemer, @tenthe, @RobertIndie, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.

**Comment by aamirxshaikh** [comment]
Hi there! I'm eager to work on this issue. Can you provide guidance on how to get started with it? @tenthe

**Comment by tenthe** [comment]
Hi @aamirxshaikh,
great that you want to work on this. As a first step, I would recommend that you check out the repository and have a look at the sample unit tests that are linked in the issue.
You can try running them first in your IDE, and then start with the implementation for the unit test for the [SwingingDoorTrendingFilterProcessor].(https://github.com/apache/streampipes/blob/752289c6acfc8fa10398c920d678c5c02143ed5c/streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/processor/sdt)

Please let me know if you need further assistance.
Cheers,
Philipp
