### ISSUE TITLE
Implement unit tests for pipeline element 'TextFilterProcessor'

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1902]
This issue is about implementing unit tests for our pipeline element [TextFilterProcessor](https://github.com/apache/streampipes/blob/752289c6acfc8fa10398c920d678c5c02143ed5c/streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/processor/textfilter).
An example of how to write unit tests for pipeline elements can be found [here](https://github.com/apache/streampipes/tree/ca4e0c2d44c1a713caaee3e9c1bff46096f41c53/streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor).

### Mentoring
As this issue is marked as a good first issue and for the `hacktoberfest` event: one of @dominikriemer, @tenthe, @RobertIndie, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.

**Comment by Aditi840** [comment]
@bossenti, can I work on this issue??

**Comment by Aditi840** [comment]
@bossenti, can I work on this issue??

**Comment by bossenti** [comment]
Sure, feel free to go ahead 🙂 

In case you need any assistance we are happy to help!

**Comment by Aditi840** [comment]
@bossenti, will you please give me an overview on what needs to be done.

**Comment by bossenti** [comment]
What are you missing or is unclear to you @Aditi840?
In my opinion, the problem description and that of the parent problem (https://github.com/apache/streampipes/issues/1884) are pretty self-explanatory.

**Comment by Aditi840** [comment]
OK @bossenti, will start working on it.

**Comment by rahulbiswas876** [comment]
@bossenti may I take up the task since it has been more than a month

**Comment by bossenti** [comment]
@rahulbiswas876 you can take on this issue
There is no one assigned currently

**Comment by rahulbiswas876** [comment]
@bossenti  please assign it to me.
