### ISSUE TITLE
Revive streampipes-maven-plugin to auto-generate pipeline element documentation

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#1906]
### Body

To keep our documentation up-to-date with existing adapters and pipeline elements, refactor the streampipes-maven-plugin:
* Auto-discover existing pipeline elements 
* Generate Docusaurus-compatible Markdown from documentation.md files
* Automatically run the plugin in the `package` phase
* Add Github action to create a pull request in `streampipes-website` with updated documentation files

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by bossenti** [comment]
PR in `streampipes-website`: https://github.com/apache/streampipes-website/pull/107
