### ISSUE TITLE
Datetime selector in Data Explorer has issues with 12 am

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1938]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

UI

### What happened?

When selecting a datetime in the data explorer, e.g., to filter data for a certain period of time, values between 12 AM and 1 AM cause a confusing representation.

### How to reproduce?

When selecting a datetime within the data explorer
<img width="920" alt="image" src="https://github.com/apache/streampipes/assets/50115603/7c43f5e5-4ec2-4f50-9447-0af13fd8e18e">

from 12 AM on
<img width="298" alt="image" src="https://github.com/apache/streampipes/assets/50115603/d93f7c52-350b-4efa-8f61-081fbf449a40">
the value is then converted to `24:00` which is confusing.
<img width="153" alt="image" src="https://github.com/apache/streampipes/assets/50115603/09830ad4-6e4a-4d69-80da-baea78fc8e17">

Even worse, when selecting a time after 12 AM
<img width="292" alt="image" src="https://github.com/apache/streampipes/assets/50115603/c3fd75ec-afe6-4a95-8e9e-839ed64be86b">
it is displayed as `24:xx` which is just wrong.
<img width="145" alt="image" src="https://github.com/apache/streampipes/assets/50115603/0946e5a2-b098-41a6-bb00-6f07bc320a60">

### Expected behavior

Datetime values between 12 AM and 1 AM should be displayed as `00:xy`.

### Are you willing to submit a PR?

None

**Comment by muyangye** [comment]
Hi @bossenti, I found the [root cause](https://github.com/moment/luxon/issues/726#issuecomment-675151145) of the problem. The backend unix timestamp is correct despite showing 24:xx, so the filter by time should still work. I have submitted a one line change PR that should fix the display problem caused by browser (tested on Chrome and Edge).

**Comment by bossenti** [comment]
thanks a lot for picking this up @muyangye 🙏🏼
