### ISSUE TITLE
Logo image broken in Footer 

### ISSUE THREAD

**Issue by sh3hz** [apache/streampipes#1983]
### Where does your observation occur?

StreamPipes Website

### What do you want to report?

Apache Software Foundation Logo image broken in Footer.

<img width="531" alt="image" src="https://github.com/apache/streampipes/assets/37012338/4fb48f60-1ecc-4baa-b9bc-9e7631546985">

### Solving the problem

https://github.com/apache/streampipes-website/blob/dev/website-v2/src/theme/Footer/index.tsx

logo: {
    alt: 'Apache Software Foundation',
    src: '/img/asf_logo_wide_small.avif',
    href: 'https://www.apache.org/',
  }

Is this just a matter of updating the href to this [link](https://svn.apache.org/repos/asf/comdev/project-logos/originals/foundation.svg)?

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by dominikriemer** [comment]
Hi  @sh3hz thanks for reporting the issue! 
I tried to reproduce the problem:
* The image path should be fine (the image can be found at https://streampipes.apache.org/img/asf_logo_wide_small.avif)
* In Chrome, the image is displayed correctly
* When opening the website in Edge, I get the same error as you reported (but I can still download the image when entering the URL directly).

So I assume it's a problem of browsers which don't display `avif` images.

Which browser are you using and can you please confirm that it's a porblem with avif files? 
https://libre-software.net/image/avif-test/#avif_test 

In this case, i think the best solution would be to convert the avif file to a good old jpeg.

**Comment by sh3hz** [comment]
Tested on Microsoft Edge Version 117.0.2045.60 (Official build) (64-bit).
Issue is with Edge not supporting `avif` rendering.

**Comment by bossenti** [comment]
Thanks for investigating @sh3hz 🙏🏼 
Are you willing to come up with a PR here?

**Comment by sh3hz** [comment]
@bossenti Can I replace with [this ](https://www.apache.org/logos/res/foundation/foundation.png)PNG as @dominikriemer suggested? or any other suggestion?

**Comment by dominikriemer** [comment]
Great - yes, or you can use the same logo as svg: https://www.apache.org/foundation/press/kit/#logo
I'm fine with both :-)
