### ISSUE TITLE
Docker compose build error

### ISSUE THREAD

**Issue by drvshavva** [apache/streampipes#2044]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

Backend

### What happened?

Error when running Docker Compose file.
 => ERROR [backend 2/2] COPY target/streampipes-core.jar  /streampipes-core.jar                                                                                           0.0s
 => CACHED [extensions-all-jvm 2/3] RUN apt-get update && apt-get install ttf-dejavu-core && apt-get install fontconfig                                                   0.0s
 => ERROR [extensions-all-jvm 3/3] COPY target/streampipes-extensions-all-jvm.jar  /streampipes-extensions-all-jvm.jar                                                    0.0s
------
 > [backend 2/2] COPY target/streampipes-core.jar  /streampipes-core.jar:
------
------
 > [extensions-all-jvm 3/3] COPY target/streampipes-extensions-all-jvm.jar  /streampipes-extensions-all-jvm.jar:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref 0ff6d0e8-262f-4ffb-8dda-6ecf70354b2a::u81ya67jpfxch147dz28rvm07: failed to walk /var/lib/docker/tmp/buildkit-mount1321444758/target: lstat /var/lib/docker/tmp/buildkit-mount1321444758/target: no such file or directory

### How to reproduce?

Run $ docker compose up -d 

### Are you willing to submit a PR?

None

**Comment by bossenti** [comment]
Hi @drvshavva,

thank you for reporting your issues with StreamPipes.
Based on the log statements you've shared, I assume that you tried to run the docker compose file in the root directory, right?

**Comment by dominikriemer** [comment]
Hi @drvshavva thanks for pointing out the error! We will investigate and fix this before the next release.

However, this docker-compose file is intended for release validation purposes only. Please use one of the docker-compose files in the installer/compose folder or (if you want to develop with StreamPipes) the cli in installer/cli.

**Comment by bossenti** [comment]
You can find more information about the officially supported installations here: https://streampipes.apache.org/docs/try-installation/

**Comment by drvshavva** [comment]
Thank you for your quick response.
