### ISSUE TITLE
Add download button for files in StreamPipes

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#2074]
### Body

StreamPipes allows the upload of files for various reasons. All uploaded files can be viewed in the module `File Management`.

<img width="906" alt="image" src="https://github.com/apache/streampipes/assets/50115603/72bd1320-4921-461d-a577-a3beea4cbfc2">

Unfortunately, there is currently no way to download a file and inspect it, in case one wants to see what the file contains.
Therefore we should add a download action directly beneath the remove action for every file.

### Mentoring

As this issue is marked as a good first issue: one of @dominikriemer, @tenthe, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue is ideal for people who are interested in getting started with StreamPipes and what to explore both worlds: the backend and the UI.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by IsaakKrut** [comment]
Hi @bossenti. I would like to contribute, could you please assign this issue to me?
