### ISSUE TITLE
Write documentation for binary message formats

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#2075]
### Body

Besides JSON StreamPipes supports other, binary event serialization formats as mentioned in our documentation: 

> Events are serialized in JSON, although StreamPipes can be configured to use other (binary) serial formats.
https://streampipes.apache.org/docs/technicals-architecture/#data-model

Let's write some documentation for the advanced user audience that would like to make use of this feature. This should encompass which message formats are supported and how they are activated.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by nitin-pandita** [comment]
@bossenti I would like to work on this issue

**Comment by bossenti** [comment]
@nitin-pandita I really appreciate your intention to contribute here! 
However, this issue requires a good understanding of the inner working of StreamPipes and one would need to really delve in our codebase. 
If you are not reluctant to do so, feel free to give it a try 🙂
But its definitely not beginner friendly

**Comment by dominikriemer** [comment]
Close as not planned
