### ISSUE TITLE
Remove magic HTTP numbers in StreamPipes

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#2092]
### Body

Due to some legacy reasons, we have HTTP status codes as hard-coded strings, e.g., `"200"` at multiple places in our code base.
To increase maintainability and readability, we want to replace all of these magic numbers by values of `org.apache.http.HttpStatus`.

The purpose of this issue is to remove all occurrences of hard-coded HTTP results and replace them with the corresponding values of `HttpStatus` code.

### Mentoring
As this issue is marked as a good first issue: one of @dominikriemer, @tenthe, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue is ideal for people who want to dip their toes in the water of open source contributions.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by bagechengzi** [comment]
Hello, I would like to contribute, can you please assign this issue to me?

**Comment by bossenti** [comment]
great to hear @bagechengzi 🎉
