### ISSUE TITLE
Display File Types in different colors

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#2107]
### Body

Within the File Management module in StreamPipes, one can directly assess the file type of each file.
<img width="821" alt="image" src="https://github.com/apache/streampipes/assets/50115603/ac9c1f72-9cc5-4689-8e0c-2e404e52ccfb">

Unfortunately, all file types are colored the same color. To provide a better overview and to distinguish different file types visually, every file type should have a different category.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by aamirxshaikh** [comment]
Hi, I'm interested in working on this issue. It would be great if you could assign it to me.

**Comment by aamirxshaikh** [comment]
Hi @bossenti,

I'm currently facing some challenges in identifying the relevant path and understanding how to run the project. Could someone provide guidance on the path navigation to locate the specific files related to this issue? Additionally, any instructions on running the project would be immensely helpful.

Thanks in advance for your assistance!

**Comment by tenthe** [comment]
@aamirxshaikh are you working on this?

**Comment by aamirxshaikh** [comment]
> @aamirxshaikh are you working on this?

Yes. @tenthe

**Comment by bossenti** [comment]
Is done
