### ISSUE TITLE
Docker install Kafka Stream Read

### ISSUE THREAD

**Issue by drvshavva** [apache/streampipes#2120]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

Connect, UI

### What happened?

Could not resolve runtime configurations from http://172.31.0.7:8001/api/v1/worker/resolvable/org.apache.streampipes.connect.iiot.protocol.stream.kafka/configurations

### How to reproduce?

`cd installer/compose
docker  compose up -d`

### Expected behavior

Kafka connection without error

### Are you willing to submit a PR?

None

**Comment by dominikriemer** [comment]
Hi @drvshavva were there any problems you had and were you able to solve it?
