### ISSUE TITLE
Cleanup extension bundles

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#2122]
### Body

Currently, we provide many different bundles of extensions as fat jars and docker images:
* Connect adapters
* Connect adapters IIoT
* Pipeline elements all jvm
* Extensions all jvm
* Extension IIoT jvm
* and more

We can harmonize these to ease the installation.

I suggest the following three "flavors" that we can offer in the standard installation:

* `extensions-all-jvm`: Includes all adapters and pipeline elements in the codebase, as well as support for all protocols (Kafka, JMS, Pulsar, MQTT, Nats)
* `extensions-all-iiot` Includes a subset of pipeline elements and adapters which are relevant for IIoT scenarios, e.g., excluding image processing and geo components and including support for all protocols
* `extensions-iiot-minimal`: A docker image minized for small image size with reduced dependencies, only relevant IIoT adapters and sinks, and only providing support for Nats as a broker.

This would allow us to also ship smaller installations so that first-time users don't need to wait too long when pulling all the docker images.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by bossenti** [comment]
@dominikriemer I really like the three flavors proposed by you!
