### ISSUE TITLE
Enhance Static Properties by UI validation

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#2144]
### Body

Currently, user input that is collected via the UI when configuring adapters & pipeline elements is not validated, e.g., for being an integer.
This can lead to frustration for the end user.
Therefore, we should try to build in validation for our static properties so that at least data types are validated automatically and maybe even additional validation criteria can be defined.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by IsaakKrut** [comment]
Hi @bossenti, I looked at the adapters creation page and saw some validation is already in place. For example: 
![image](https://github.com/apache/streampipes/assets/25233902/914c3e24-e508-433e-93fb-49f4daaf0be8)

Could you please clarify what properties you are referring to and where they can be found?

**Comment by tenthe** [comment]
Hi @IsaakKrut,
can you please check if the validation also validates that the input is an integer?
Is there an error message when you enter "9092.0"?

**Comment by IsaakKrut** [comment]
@tenthe it does not, but it shows an error with exception stack trace when it tries to connect and guess the schema. I did find 3 adapters that do not have UI validation on their port fields: OPC UA, PLC4X MODBUS, ROS Bridge

**Comment by tenthe** [comment]
Ok great. Then this is a good starting point for this issue
