### ISSUE TITLE
 Implement E2E Tests for Enhanced Adapter Deletion

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#2151]
### Body

Issue #1936 introduced several new features related to adapter deletion. 
To ensure the robustness of these new functionalities, we need to implement End-to-End (E2E) tests that cover all aspects of adapter deletion.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by muyangye** [comment]
Let me implement these tests since it's a relatively new feature!
