### ISSUE TITLE
How to start streampipes locally using the source code

### ISSUE THREAD

**Issue by selectbook** [apache/streampipes#2168]
### Where does your observation occur?

None

### What do you want to report?

I still don't know how to start streampipes locally using the source code, and I haven't found relevant information in the documentation either.

### Are you willing to submit a PR?

None

**Comment by obermeier** [comment]
Hi @selectbook,

to run StreamPipes from source code the documentation in the repository could be possibly useful [Link](https://github.com/apache/streampipes#building-streampipes).

Don't hesitate to ask if you have more questions.

BR,
Stefan

**Comment by bossenti** [comment]
In addition, if you want to run parts/services of StreamPipes within your IDE for debugging purpose, the following instruction should help you: https://cwiki.apache.org/confluence/display/STREAMPIPES/Core
