### ISSUE TITLE
Add download button for assets in StreamPipes

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#2192]
### Body

StreamPipes allows the creation so called assets. All assets can be viewed in the module `Assets`.

![image](https://github.com/apache/streampipes/assets/50115603/ed1791b3-3107-48e9-bdd3-1cc2975a47d3)

Unfortunately, this view currently does not allow to download an asset directly.
Therefore we should add a download action directly beneath the remove action for every file.

Similar to #2074 

### Mentoring

As this issue is marked as a good first issue: one of @dominikriemer, @tenthe, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue is ideal for people who are interested in getting started with StreamPipes and what to explore both worlds: the backend and the UI.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by IsaakKrut** [comment]
@bossenti Is this supposed to be the same functionality as export on /#/configuration/export page and download a zip file or just the asset object in json format is fine?

**Comment by bossenti** [comment]
Hm, in my mind it should have the same functionality as in /#/configuration/export
This would then allow to import the downloaded asset there as well.
But I'm open to discuss this.
