### ISSUE TITLE
FIle upload does not allow for multiple files

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#2221]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

UI

### What happened?

When selecting multiple files in the file management component to be uploaded, only the latest is really uploaded.

### How to reproduce?

Go to the file management module and click on `upload new file`.
Select multiple files in the upload dialog.
![image](https://github.com/apache/streampipes/assets/50115603/d08d9a48-0b6b-49a9-9b52-f79035a55f6f)
Press the `IMPORT FILES` button
![image](https://github.com/apache/streampipes/assets/50115603/07f821aa-2ece-41b3-8acf-afb413dd8b56)

instead of both files only one appears to be uploaded

### Expected behavior

Either clearly indicate that only one file is allowed per upload by changing button labelings and the upload dialog or enable the upload of multiple files.

### Are you willing to submit a PR?

None

**Comment by bossenti** [comment]
### Mentoring

As this issue is marked as a good first issue: one of @dominikriemer, @tenthe, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue is ideal for people who are interested in getting started with StreamPipes and have some prior knowledge in UI development.

**Comment by aamirxshaikh** [comment]
I tried to reproduce the issue on my local, but I was able to upload multiple files successfully. Here is a screenshot:

![image](https://github.com/apache/streampipes/assets/56036364/ff30d4f0-5b57-43c5-9709-799c3f5988f5)

![image](https://github.com/apache/streampipes/assets/56036364/29eaa004-d789-4385-bfc9-fedbfb7dee15)

**Comment by bossenti** [comment]
Hm, that's strange 😅

I'll give it another try on my end, maybe it's related to the specific file I used

**Comment by muyangye** [comment]
As I was fixing #2181, I encountered the exact same problem which broke my code. Let me fix them altogether.

**Comment by bossenti** [comment]
Mhm okay, thanks a lot for investigating @muyangye  🙏🏼
