### ISSUE TITLE
Enhance Data Lake Sink Schema Management Options

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#2252]
## Current Behavior:

In the current version, the `Data Lake Sink` utilizes the `TimeSeriesStore` to write events to the time series storage (InfluxDB). When the `event schema` of the pipeline changes, the new `event schema` is stored for the pipeline.

In `DataExplorerSchemaManagement.createMeasurement`, it checks if there is already a schema for the measure name. If a schema exists, it gets updated; otherwise, a new entry is created.

## Proposed Enhancement:

Introduce a user-configurable option within the Data Lake Sink, presented as radio buttons, to choose between two schema management strategies:

- **Option 1 (Default):** Update the schema of the `DataLakeMeasure` when it changes.
    
- **Option 2:** Extend the existing event schema. This option should only append new and changing fields without removing existing ones.
    

This enhancement provides users with more flexibility in managing schema changes based on their specific requirements.
Especially users will be able to see old data in the `data explorer` even when the schema changed.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by bossenti** [comment]
Great suggestion @tenthe 🙏🏼 

Which option would we select for the persist-pipeline which is automatically created on user request during the adapter creation?
