### ISSUE TITLE
Harmonize `InfluxStore` and `InfluxDbClient`

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#2354]
### Body

Both classes seem to provide similar (or even the same?) functionalities but to different extents and with different parametrization capabilities.
We should try to harmonize both classes and remove duplicated code.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by IsaakKrut** [comment]
Hi @bossenti,

I can't find the InfluxStore class. I only see some generated files in streampipes-data-explorer-commons: documentation file InfluxStore.html and an already compiled class InfluxStore.class. Where are those files being generated from and how can I find out where the class is being used?

**Comment by tenthe** [comment]
Hi @IsaakKrut,
it seems that the class has been renamed to `TimeSeriesStorageInflux`.
Maybe you can check if this issue is still relevant or if we can close it.
