### ISSUE TITLE
MQTT showing "Device cannot be connected"

### ISSUE THREAD

**Issue by arun-eglabs** [apache/streampipes#2422]
### Apache StreamPipes version

0.92.0

### Affected StreamPipes components

Connect

### What happened?

I was trying to connect via MQTT 

 Broker: broker.hivemq.com
TCP Port: 1883

it shows timeout , the broker is running fine. 

Should we do anything in docker to enable the connectivity? from streampipe to internet inside docker network 

### Are you willing to submit a PR?

None

**Comment by obermeier** [comment]
Hi @arun-eglabs,

Thank you very much for your feedback!

Normally, external networks should be reachable from the containers.

One "common" cause of this error could be a timeout when the MQTT-Adapter is trying to determine the event schema. This issue often occurs if no data are published during the schema-guessing phase.

Could you please provide the content of the  "Error details" window if this issue persists?

Cheers,
Stefan

**Comment by arun-eglabs** [comment]
Thanks a lot for the quick update, I updated to the new version and it is working, however, I will check again and see if the data is flowing continuously, sometimes we face issues where the data is not continuously flowing etc. 

But will keep you posted.... or we may close this bug 

We would like to contribute to the product, the build failed when we compiled it. Do we have a different code base for contributing to it, please ?  And can we raise queries if the build failed with giving the errors

**Comment by dominikriemer** [comment]
Hi @arun-eglabs great that you were able to get it working!
Where exactly does your build fail? In most cases, it should be just a `mvn package` for the Java part and `npm install` followed by `npm run build` for the UI part.
Did any of these commands fail in your setup?

Cheers
Dominik
