### ISSUE TITLE
apachestreampipes/pipeline-elements-all-flink:0.93.0 not found

### ISSUE THREAD

**Issue by kruscho** [apache/streampipes#2429]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

Connect

### What happened?

Can´t run the full docker-compose file, because .env defines 0.93. This tag does not exist for pipeline-elements-all-flink in docker-hub. Please update tag in docker hub. 
Workaround: edit docker-compose.full.yml and adjust tag:

pipeline-elements-all-flink:
  image: "${SP_DOCKER_REGISTRY}/pipeline-elements-all-flink:${SP_VERSION}"

to

pipeline-elements-all-flink:
  image: "${SP_DOCKER_REGISTRY}/pipeline-elements-all-flink:0.93.0-SNAPSHOT"

### How to reproduce?

`docker compose -f docker-compose.full.yml up`

log:
Error response from daemon: manifest for apachestreampipes/pipeline-elements-all-flink:0.93.0 not found: manifest unknown: manifest unknown

### Expected behavior

just running as expected

### Are you willing to submit a PR?

None

**Comment by obermeier** [comment]
Hi @kruscho, 
thank you verry much for opening this issue. 
The Flink pipeline elements are currently not supported, due to version incompatibilities (#1740).

In the meantime, I propose to remove it from the compose file. (#2432)

**Comment by obermeier** [comment]
Due to resolution in #2432, the error should not occur again.
