### ISSUE TITLE
Buttons in time range selection not functioning

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#2442]
### Body

The next and previous buttons within the time range selection of the data explorer are unresponsive. Clicking on either button does not trigger any action.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by IsaakKrut** [comment]
Hi @tenthe,

Is it these buttons?
![Screenshot_2](https://github.com/apache/streampipes/assets/25233902/ee20a12b-0566-418c-aa4d-4d9b055258c6)


Could you assign this issue to me?

**Comment by tenthe** [comment]
Yes, these are the buttons.
