### ISSUE TITLE
TestBooleanCounterProcessor

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#2545]

**Comment by nine03** [comment]
@tenthe 
Thank you for your prompt response.

**Comment by tenthe** [comment]
@nine03, we usually use the default branch name created by GitHub.
In this case `2545-testbooleancounterprocessor`.

**Comment by tenthe** [comment]
@nine03 just a quick note in case you have already forked the project. I have just merged the PR with JUnit 5 into the Dev branch.

**Comment by nine03** [comment]
@tenthe 
I created a new branch 2545-testbooleancounterprocessor and I'm working in that branch.

**Comment by nine03** [comment]
@tenthe 
Hi, I'm a little doubtful that I'm writing the code correctly, could you do a code review for me?
Can I just post the code here or do I need to PR it? There's an error in the code to do a PR.

**Comment by tenthe** [comment]
Hi @nine03, 
I think the easiest way is to create a PR. You can also mark it as a draft.
Cheers,
Philipp

**Comment by nine03** [comment]
@tenthe 
Hi ! I made a pull request #2557 .

**Comment by nine03** [comment]
@tenthe
Hi ! I made a pull request https://github.com/apache/streampipes/pull/2557 .

**Comment by nine03** [comment]
I'm sorry. I tried to resolve this issue but I don't think I can properly solve it. The problem seems more complex and difficult than I thought. Clearly more effort was needed, but there seems to be a limit to what I can do with my abilities.

**Comment by tenthe** [comment]
@nine03, no worries. Thank you very much for your input.
If you want to work on another issue, just get in touch.
