### ISSUE TITLE
When Extensions are used, starting multiple "service" can result in multiple identical elements in the ui

### ISSUE THREAD

**Issue by wyyolo** [apache/streampipes#2556]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

Backend

### What happened?

When Extensions are used, starting multiple "service" can result in multiple identical elements in the ui.
![9975b7cb6d412e37628c82050c7229d](https://github.com/apache/streampipes/assets/105999518/0e53bd58-0442-4b59-bbd6-354f337a1496)

### Are you willing to submit a PR?

None

**Comment by dominikriemer** [comment]
@wyyolo this should have been resolved by PR #2645

**Comment by bossenti** [comment]
closed by #2645
