### ISSUE TITLE
[Documentation] SDK Reference examples change from Labels.from to withID syntax

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#266]
SDK References examples and text are using the deprecated  Labels.from method in required stream and output strategy.

Has to be rewritten with withID useage:
 
https://streampipes.apache.org/docs/docs/dev-guide-stream-requirements/

Imported from Jira [STREAMPIPES-122](https://issues.apache.org/jira/browse/STREAMPIPES-122). Original Jira may contain additional context.
Reported by: micklich.

**Comment by bossenti** [comment]
outdated
