### ISSUE TITLE
No user feedback when self registration fails

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#2661]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

UI

### What happened?

If the self-registration of a new user fails, e.g, due to misconfigured Email settings, the UI does not display any feedback, whereas it does when the user already exists.
![email-registration](https://github.com/apache/streampipes/assets/50115603/de37844a-1f27-4085-971b-85b0df727ddf)

### Expected behavior

Show an error message in the UI for internal errors (response code 500) as well

### Are you willing to submit a PR?

No, I don't want to submit a PR.

**Comment by IsaakKrut** [comment]
Hi @bossenti. could you help me reproduce this? I enabled registration by manually returning true in the RegistrationAllowedCanActivateGuard class. But I'm getting 403 returned from the backend. Do you know what could be the issue? Additionally, how can I reproduce 500 errors specifically?

**Comment by bossenti** [comment]
Have you enabled self-configuration via the UI and configured the email settings? 
![image](https://github.com/apache/streampipes/assets/50115603/37b35449-25e1-4b63-a21b-7e3a8f65cb5f)

![image](https://github.com/apache/streampipes/assets/50115603/39342f1e-c07e-43ba-b59e-4b254c7f97ea)

This is required that the self registration is activated. Then StreamPipes tries to send an email to the new user asking for confirmation. If the Email server is configured wrongly, the email dispatching fails, the backend should return a 500 error code

Hope this helps 🙂
