### ISSUE TITLE
Unit testing framework updates

### ISSUE THREAD

**Issue by IsaakKrut** [apache/streampipes#2737]
### Body

Related to #2374 

As discussed in PR #2730

- Move ProcessingElementTestExecutor into the module streampipes-test-utils
- Create a builder for userConfigurations parameter
- Hide the prefixes inside userConfigurations

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by IsaakKrut** [comment]
Hi @tenthe, 

I pushed my changes to the branch apache:2374-provide-a-framework-to-easily-unit-test-processing-elements. I am having issues with moving the code to a different module. When I tried moving it to streampipes-test-utils I had errors with cyclic dependencies. I created a new module streampipes-test-utils-executors, but getting this  error: 
The following artifacts could not be resolved: org.apache.streampipes:streampipes-test-utils-executors:jar:tests:0.95.0-SNAPSHOT (absent): org.apache.streampipes:streampipes-test-utils-executors:jar:tests:0.95.0-SNAPSHOT was not found in https://repository.apache.org/snapshots 

How should I proceed with that?


Regarding the functionality you can see commit https://github.com/apache/streampipes/commit/c25b1bee61ce3a5dc366344024f00056ec957e8a

All tests are working. I have identified 4 scenarios for the selector prefix:

1. Default. By default the prefix will be an empty string
2. SAME_PREFIX. Will use s0 for all events
3. ALTERNATE. Will alternate between s0 and s1
4. Custom. Accepts a list of prefixes that will be iterated over during event generation.

I assume after the issue with maven modules is fixed I can create a PR from 2374-provide-a-framework-to-easily-unit-test-processing-elements to the dev branch

**Comment by tenthe** [comment]
Hi @IsaakKrut,

thank you for the changes. 
I will have a look at them, but will take until next week.

Cheers,
Philipp

**Comment by bossenti** [comment]
Closed by https://github.com/apache/streampipes/pull/2375
