### ISSUE TITLE
TestTrendProcessor

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#2775]

**Comment by pambrocio** [comment]
please assign this to me

**Comment by pambrocio** [comment]
Build successful

'''
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache StreamPipes 0.95.0-SNAPSHOT:
[INFO] 
[INFO] Apache StreamPipes ................................. SUCCESS [  1.860 s]
[INFO] streampipes-archetype-extensions-jvm ............... SUCCESS [  0.744 s]
[INFO] streampipes-archetype-pe-sinks-flink ............... SUCCESS [  0.082 s]
[INFO] streampipes-archetype-pe-processors-flink .......... SUCCESS [  0.068 s]
[INFO] StreamPipes Commons ................................ SUCCESS [  2.894 s]
[INFO] streampipes-model-shared ........................... SUCCESS [  0.946 s]
[INFO] streampipes-vocabulary ............................. SUCCESS [  1.591 s]
[INFO] streampipes-model .................................. SUCCESS [  4.389 s]
[INFO] streampipes-dataformat ............................. SUCCESS [  1.011 s]
[INFO] streampipes-messaging .............................. SUCCESS [  0.895 s]
[INFO] streampipes-client-api ............................. SUCCESS [  1.065 s]
[INFO] streampipes-dataformat-json ........................ SUCCESS [  0.902 s]
[INFO] streampipes-dataformat-cbor ........................ SUCCESS [  0.872 s]
[INFO] streampipes-dataformat-fst ......................... SUCCESS [  0.856 s]
[INFO] streampipes-security-jwt ........................... SUCCESS [  0.978 s]
[INFO] streampipes-model-client ........................... SUCCESS [  0.612 s]
[INFO] streampipes-extensions-api ......................... SUCCESS [  1.493 s]
[INFO] streampipes-test-utils ............................. SUCCESS [  1.116 s]
[INFO] streampipes-serializers-json ....................... SUCCESS [  1.235 s]
[INFO] streampipes-client ................................. SUCCESS [  1.108 s]
[INFO] streampipes-measurement-units ...................... SUCCESS [  1.706 s]
[INFO] streampipes-sdk .................................... SUCCESS [  3.354 s]
[INFO] streampipes-connect-shared ......................... SUCCESS [  2.098 s]
[INFO] streampipes-service-discovery-api .................. SUCCESS [  0.951 s]
[INFO] streampipes-dataformat-smile ....................... SUCCESS [  0.831 s]
[INFO] streampipes-storage-api ............................ SUCCESS [  1.096 s]
[INFO] streampipes-storage-couchdb ........................ SUCCESS [  2.272 s]
[INFO] streampipes-storage-management ..................... SUCCESS [  0.885 s]
[INFO] streampipes-user-management ........................ SUCCESS [  1.649 s]
[INFO] streampipes-mail ................................... SUCCESS [  1.228 s]
[INFO] streampipes-resource-management .................... SUCCESS [  2.313 s]
[INFO] streampipes-service-discovery ...................... SUCCESS [  0.874 s]
[INFO] streampipes-pipeline-management .................... SUCCESS [  3.293 s]
[INFO] streampipes-connect-management ..................... SUCCESS [  2.816 s]
[INFO] streampipes-extensions-management .................. SUCCESS [  2.772 s]
[INFO] streampipes-data-explorer-commons .................. SUCCESS [  2.617 s]
[INFO] streampipes-data-explorer .......................... SUCCESS [  2.099 s]
[INFO] streampipes-data-export ............................ SUCCESS [  1.570 s]
[INFO] streampipes-service-base ........................... SUCCESS [  1.041 s]
[INFO] streampipes-rest-shared ............................ SUCCESS [  1.033 s]
[INFO] streampipes-rest-extensions ........................ SUCCESS [  2.033 s]
[INFO] streampipes-service-extensions ..................... SUCCESS [  1.427 s]
[INFO] Apache StreamPipes Maven Plugin .................... SUCCESS [  3.895 s]
[INFO] streampipes-extensions ............................. SUCCESS [  0.008 s]
[INFO] streampipes-connectors-mqtt ........................ SUCCESS [  1.180 s]
[INFO] streampipes-pipeline-elements-shared ............... SUCCESS [  0.746 s]
[INFO] streampipes-connect-adapters ....................... SUCCESS [  0.794 s]
[INFO] streampipes-connect-adapters-iiot .................. SUCCESS [  2.104 s]
[INFO] streampipes-wrapper ................................ SUCCESS [  1.365 s]
[INFO] StreamPipes Wrapper for Standalone Pipeline Element Implementations SUCCESS [  1.449 s]
[INFO] streampipes-connectors-influx ...................... SUCCESS [  1.265 s]
[INFO] streampipes-messaging-kafka ........................ SUCCESS [  1.080 s]
[INFO] streampipes-connectors-kafka ....................... SUCCESS [  1.273 s]
[INFO] streampipes-messaging-nats ......................... SUCCESS [  0.916 s]
[INFO] streampipes-connectors-nats ........................ SUCCESS [  1.032 s]
[INFO] streampipes-connectors-opcua ....................... SUCCESS [  2.854 s]
[INFO] streampipes-connectors-pulsar ...................... SUCCESS [  2.742 s]
[INFO] streampipes-connectors-rocketmq .................... SUCCESS [  2.396 s]
[INFO] streampipes-connectors-tubemq ...................... SUCCESS [  1.117 s]
[INFO] streampipes-processors-filters-jvm ................. SUCCESS [  3.043 s]
[INFO] streampipes-connectors-plc ......................... SUCCESS [  1.858 s]
[INFO] streampipes-messaging-mqtt ......................... SUCCESS [  0.891 s]
[INFO] streampipes-messaging-pulsar ....................... SUCCESS [  1.013 s]
[INFO] streampipes-wrapper-siddhi ......................... SUCCESS [  2.081 s]
[INFO] streampipes-processors-filters-siddhi .............. SUCCESS [  4.214 s]
[INFO] streampipes-processors-transformation-jvm .......... SUCCESS [  4.190 s]
[INFO] streampipes-messaging-jms .......................... SUCCESS [  0.918 s]
[INFO] streampipes-sinks-brokers-jvm ...................... SUCCESS [  1.371 s]
[INFO] streampipes-sinks-databases-jvm .................... SUCCESS [  2.038 s]
[INFO] streampipes-sinks-internal-jvm ..................... SUCCESS [  2.295 s]
[INFO] streampipes-sinks-notifications-jvm ................ SUCCESS [  2.775 s]
[INFO] streampipes-processors-enricher-jvm ................ SUCCESS [  1.810 s]
[INFO] streampipes-processors-change-detection-jvm ........ SUCCESS [  1.175 s]
[INFO] streampipes-extensions-all-iiot .................... SUCCESS [  2.300 s]
[INFO] streampipes-processors-image-processing-jvm ........ SUCCESS [  1.491 s]
[INFO] streampipes-processors-text-mining-jvm ............. SUCCESS [  1.333 s]
[INFO] streampipes-processors-geo-jvm ..................... SUCCESS [  1.877 s]
[INFO] streampipes-extensions-all-jvm ..................... SUCCESS [  3.290 s]
[INFO] streampipes-extensions-iiot-minimal ................ SUCCESS [  1.652 s]
[INFO] StreamPipes Integration Tests ...................... SUCCESS [ 25.711 s]
[INFO] streampipes-rest-core-base ......................... SUCCESS [  1.005 s]
[INFO] StreamPipes REST API ............................... SUCCESS [  2.333 s]
[INFO] streampipes-platform-services ...................... SUCCESS [  1.257 s]
[INFO] streampipes-sdk-bundle ............................. SUCCESS [  0.178 s]
[INFO] StreamPipes Core ................................... SUCCESS [  2.621 s]
[INFO] streampipes-service-core-minimal ................... SUCCESS [  1.142 s]
[INFO] streampipes-wrapper-distributed .................... SUCCESS [  1.029 s]
[INFO] StreamPipes Wrapper for Apache Flink ............... SUCCESS [  1.671 s]
[INFO] streampipes-wrapper-kafka-streams .................. SUCCESS [  1.247 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:51 min
[INFO] Finished at: 2024-04-25T13:16:38+08:00
[INFO] ------------------------------------------------------------------------
paulo@PRED:~/ASF/streampipes$ git status
On branch 2775-fix-TestTrendProcessor
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   streampipes-extensions/streampipes-processors-filters-siddhi/pom.xml
        modified:   streampipes-extensions/streampipes-processors-filters-siddhi/src/test/java/org/apache/streampipes/processors/siddhi/trend/TestTrendProcessor.java

no changes added to commit (use "git add" and/or "git commit -a")
paulo@PRED:~/ASF/streampipes$ 
'''

**Comment by pambrocio** [comment]
PR https://github.com/apache/streampipes/pull/2789
