### ISSUE TITLE
Pipeline loosing connections

### ISSUE THREAD

**Issue by FabriceHansen** [apache/streampipes#2817]
### Apache StreamPipes version

Other StreamPipes version (please specify below)

### Affected StreamPipes components

Connect

### What happened?

Pipeline loosing connections between data processors and data sinks despite the fact that the pipeleine was running properly before edition.

### How to reproduce?

The problem occured once I tried to introduce a Trend Data Processor. After deleting the Trend block and reconnecting the blocks, I was able to save and run the pipeline but everytime I open it in edition mode, connections are lost. 

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by tenthe** [comment]
@dominikriemer, is this also addressed in #2816?
