### ISSUE TITLE
Asset Dashboard loosing picture when going to Edit mode

### ISSUE THREAD

**Issue by FabriceHansen** [apache/streampipes#2820]
### Apache StreamPipes version

Other StreamPipes version (please specify below)

### Affected StreamPipes components

UI

### What happened?

In V0.93, Asset Dashboard loosing picture when going to Edit mode

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by tenthe** [comment]
Hi @FabriceHansen,

thank you for reporting the issue. 
The asset dashboard was deprecated and will be removed in the future as there are several functionalities that are not working properly.
