### ISSUE TITLE
Cannot start a pipeline with a Notification data sink

### ISSUE THREAD

**Issue by michaelreisvoid** [apache/streampipes#3004]
### Apache StreamPipes version

Other StreamPipes version (please specify below)

### Affected StreamPipes components

Backend, Processing Elements, UI

### What happened?

in version 0.95, when I create a pipeline with a Notification data sink, or an Email Notification data sink, I can't start the pipeline, an error is displayed. 

### How to reproduce?

Create a pipeline with a Notification data sink, and then try to start the pipeline.

### Expected behavior

Pipeline is started and notifications are stored.

### Additional technical information

This happens with 0.95
This does not happen with 0.93

The following stacktrace is logged:

```
extensions-all-jvm-1  | java.lang.NullPointerException: Cannot invoke "org.apache.streampipes.model.staticproperty.FreeTextStaticProperty.getValue()" because the return value of "org.apache.streampipes.sdk.extractor.AbstractParameterExtractor.getStaticPropertyByName(String, java.lang.Class)" is null
extensions-all-jvm-1  | 	at org.apache.streampipes.sdk.extractor.AbstractParameterExtractor.singleValueParameter(AbstractParameterExtractor.java:122)
extensions-all-jvm-1  | 	at org.apache.streampipes.wrapper.standalone.StreamPipesNotificationSink.onInvocation(StreamPipesNotificationSink.java:87)
extensions-all-jvm-1  | 	at org.apache.streampipes.sinks.internal.jvm.notification.InternalStreamPipesNotificationSink.onInvocation(InternalStreamPipesNotificationSink.java:57)
extensions-all-jvm-1  | 	at org.apache.streampipes.wrapper.standalone.StreamPipesDataSink.onPipelineStarted(StreamPipesDataSink.java:37)
```

### Are you willing to submit a PR?

None

**Comment by tenthe** [comment]
Hi @michaelreisvoid,

thanks for opening the issue.

I attempted to reproduce the problem on a new instance of StreamPipes version `0.95.0`. I created a `machine data simulator` adapter and a `Notifications` sink, and the pipeline started and worked as expected.

Could you clarify your setup? Did you set up a new StreamPipes instance, or did you migrate from version 0.93.0 to 0.95.0? If you migrated, did you update all of the Docker services or only the backend?
Were there any error logs during the migration process?

**Comment by michaelreisvoid** [comment]
Hi @tenthe , 
thanks for the followup

I am using the release directly, running locally with docker compose:
`cd ~/apache-streampipes-0.95.0/installer/compose`
`docker compose up` 
so everything should be up to date. I just ran a `docker system prune -a` to be extra sure, and the error still occurs.

I was using the mqtt adaptor, but I just tried with the machine data simulator, and still run into the same issue. 

I can create the pipeline, `Enable live preview` works, the exception just happens when trying to start the pipeline. A colleague of mine also has the same issue. 
We just connect an adaptor to a `Notification`, and this happens every time.

**Comment by michaelreisvoid** [comment]
@tenthe 

Ok, I also prunes all of my volumes, repeated the steps, and now it works as expected. 
Personally this now becomes a non-issue, but it seems there is some sort of a consistency problem when using the same volumes from one version to the next

**Comment by tenthe** [comment]
@michaelreisvoid, ok. Thanks for the information, also if you have any further questions please feel free to ask.

If anyone else is facing this issue during the update from 0.93.0 to 0.95.0, please feel free to reopen this issue.
