### ISSUE TITLE
NullPointer in DataLakeMeasureResourceV4.getDataLakeInfos

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#3072]
### Body

In `DataLakeMeasureResourceV4.getDataLakeInfos` (/api/v4/datalake/measure?filter=measurementName), a NullPointerException occurs if the `measurementName` does not exist. 
The API should return an error message indicating that there is no measure with the provided `measurementName`.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by Sylvain2703** [comment]
This issue also occurs when the `filter` query param is not provided (eg. `/api/v4/datalake/measure`). I tried without `filter` parameter because the OpenAPI definition doesn't mention it as required.

**Comment by tenthe** [comment]
Ok, thanks, I have marked this parameter as mandatory. Since the API endpoint and the parameters are somewhat unfavorably named, I will also change this. I will describe the change in the PR.
