### ISSUE TITLE
java.lang.IndexOutOfBoundsException when passing data through the user-defined pipeline element

### ISSUE THREAD

**Issue by Skydreamer-123** [apache/streampipes#3222]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

Processing Elements

### What happened?

Version: 0.97

Firstly, I have started my custom pipeline element. 
Second, when my pipeline element was connected and as the first data flowed through, I got the following exception: [Exception.log](https://github.com/user-attachments/files/16961318/Exception.log)

Source Code (little to no changes to the original files from the Maven archetype): 
[DataProcessor.zip](https://github.com/user-attachments/files/16961379/DataProcessor.zip)

### Are you willing to submit a PR?

None

**Comment by dominikriemer** [comment]
Hi @Skydreamer-123 which version do you use in the Maven archetype and what is your StreamPipes version? Is it both 0.97.0-SNAPSHOT?

**Comment by nicolasperivolaris** [comment]
@Skydreamer-123 I got the same problem. Version 0.95.0 is not compatible with 0.97.0-SNAPSHOT. 

I had to compile Streampipes and use 0.97.0-SNAPSHOT in my extension's pom.xml.

**Comment by dominikriemer** [comment]
@Skydreamer-123 @nicolasperivolaris this accounts for all releases as well, while upgrades from one version to the next version are supported, the extension service version must always match the version of the core.
If you don't want to compile the whole platform when using a SNAPSHOT version for development purposes in an internal extension, you can also use the Snapshot repo, where we push our nightly builds: https://repository.apache.org/content/repositories/snapshots/
