### ISSUE TITLE
Unable to save pipeline with a long name

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#3252]
### Body

When a user tries to store a pipeline with a long name, the save action is blocked.

## Steps to reproduce
1. Create or edit a pipeline.
2. Enter a long name for the pipeline.
3. Observe that saving is not possible.

## Expected behavior
A message should inform the user that the pipeline name is too long.

![grafik](https://github.com/user-attachments/assets/836ccefc-eeec-4757-8091-67d90b62f1c9)

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by ethanernst11** [comment]
I can take this issue.

**Comment by tenthe** [comment]
Hi @ethanernst11,
you can start in the component `SavePipelineSettingsComponent`. 
This contains the logic of the pipeline start menu.
If you have any questions, please feel free to ask.
Cheers,
Philipp
