### ISSUE TITLE
Support change of username and password in profile view

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#655]
In the profile view, a user should be able to change the own password and to modify the mail address used as the username.

Imported from Jira [STREAMPIPES-511](https://issues.apache.org/jira/browse/STREAMPIPES-511). Original Jira may contain additional context.
Reported by: riemer.

**Comment by curichan** [comment]
Hi Dominik, many thanks for providing streampipes! It would appear that this functionality does not work for a non-admin user. 
![image](https://user-images.githubusercontent.com/101100671/236239974-92e9fa2c-dc05-4592-a81b-e720b90d6fbc.png)

**Comment by tenthe** [comment]
Thanks a lot for reporting this @curichan. I'll reopen the issue till this problem is fixed.

**Comment by bossenti** [comment]
Thanks a lot for reporting @curichan!
Would you be interested in contributing here? 
If so, we would guide you how to solve the issue 🙂

**Comment by dominikriemer** [comment]
Thank you @curichan for reporting this!
I've create a PR to fix this and it should be available in the dev branch soon.
