### ISSUE TITLE
Enable connect adapter service development when core runs in Docker

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#686]
Opposed to processors and sinks that are passively registered by the core of StreamPipes via the service discovery feature in Consul, connect adapter services actively register their service description at the core service. Therefore, the URL of the core is retrieved via Consul which points to the core container IP address (commonly "http://172.x.x.x:8030") which can't be resolved from the local IDE environment.

*Option A*

Adapter developers can manipulate the docker-compose description of the backend service by adding an "SP_HOST" environment variable with their local machine's IP address. Thereby, the core of StreamPipes registers under this IP at Consul which can be resolved from the local IDE, e.g., with the URL "http://192.x.x.x:8030".

*Option B*

Adapter developers can simply use the "SP_DEBUG=true" environment variable in the run configuration of a connect adapter service to remap the retrieved URL from "http://172.x.x.x:8030" to "http://localhost:8030". 

 

Note: this allows applies for hybrid service definitions containing, e.g., extensions-all-jvm, as it contains adapter services that currently try to actively register at the core.

Imported from Jira [STREAMPIPES-523](https://issues.apache.org/jira/browse/STREAMPIPES-523). Original Jira may contain additional context.
Reported by: wiener.

**Comment by bossenti** [comment]
This is already possible
