### ISSUE TITLE
Remove lodash dependency from ui

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#690]
The lodash dependency is used in "PipelineElementOptionsComponent" where the cloneDeep function is imported.

 

 

Imported from Jira [STREAMPIPES-525](https://issues.apache.org/jira/browse/STREAMPIPES-525). Original Jira may contain additional context.
Reported by: zehnder.

**Comment by mohitbhagat** [comment]
Hi @bossenti @dominikriemer , I'm not sure what's expected here. I notice some usages of lodash in `pipeline-element-options.component.ts`. We are using cloneDeep from lodash, to do some deep cloning. Am I expected to replace cloneDeep with a custom clone method? What's the reason behind wanting to get rid of the lodash dependency?

**Comment by bossenti** [comment]
Unfortunately, I cannot provide any support here.
@dominikriemer probably knows best about this topic
