### ISSUE TITLE
Two pipelines can write into the same measurement with different event schema

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#728]
No error ist displayed when two pipelines write into one data lake measurement with a different event schema.

The user should get a notification that this is not possible

Imported from Jira [STREAMPIPES-568](https://issues.apache.org/jira/browse/STREAMPIPES-568). Original Jira may contain additional context.
Reported by: zehnder.

**Comment by bossenti** [comment]
This is solved by #2252
