### ISSUE TITLE
Python client deployment concept

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#766]
Define a general release process for the Python client.
Prepare all requirements (e.g., PyPi account etc.)

 

IMPORTANT: This task should only be done in close consultation with the mailing list and no one should tackle it on their own.
Do not create or publish Python artifacts without being approved by a vote on the mailing list!

Imported from Jira [STREAMPIPES-610](https://issues.apache.org/jira/browse/STREAMPIPES-610). Original Jira may contain additional context.
Reported by: bossenti.

**Comment by bossenti** [comment]
no longer relevant
