### ISSUE TITLE
Refactor processing elements

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#775]
Refactor Pipeline elements from three-class approach to one class approach.

Imported from Jira [STREAMPIPES-615](https://issues.apache.org/jira/browse/STREAMPIPES-615). Original Jira may contain additional context.
Reported by: bossenti.

**Comment by dominikriemer** [comment]
The following subtask(s) are associated with this issue: #776, #777

**Comment by bossenti** [comment]
Is a duplicate of #1315
