### ISSUE TITLE
Upgrade Flink version to latest 1.16

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#799]
Imported from Jira [STREAMPIPES-644](https://issues.apache.org/jira/browse/STREAMPIPES-644). Original Jira may contain additional context.
Reported by: vesense.

**Comment by bossenti** [comment]
Related PR: #151

**Comment by tenthe** [comment]
@bossenti do you think we should add a label PR available?

**Comment by bossenti** [comment]
In the mean time I've discovered that it is even better to connect to the PR on the right side bar (if the PR misses the link to the ticket) :) 
Just added this

**Comment by tenthe** [comment]
Ah very cool, thanks
