### ISSUE TITLE
Update REST API for data streams

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#801]
As discussede in PR [1] change default route from "/v2/streams/own" to "/v2/streams"to get the data streams 

 

[1] https://github.com/apache/streampipes/pull/141

Imported from Jira [STREAMPIPES-649](https://issues.apache.org/jira/browse/STREAMPIPES-649). Original Jira may contain additional context.
Reported by: zehnder.

**Comment by bossenti** [comment]
Related PR: #155
