### ISSUE TITLE
Enable check style for the project

### ISSUE THREAD

**Issue by RobertIndie** [apache/streampipes#820]
### Body

This is the issue to track the progress of check-style enablement for all modules. 
If you want to take over some of the modules, please feel free to leave a comment here. And thanks for all your contribution!  :smiley:

Only the first level of sub-modules are listed here. If you feel that some of the modules(eg. `streampipes-extensions`) are heavy, please continue to split them into smaller tasks in this issue.

- [x] #830
- [x] #832
- [x] #833
- [x] #834
- [x] streampipes-service-discovery-api https://github.com/apache/streampipes/pull/845
- [x] streampipes-logging https://github.com/apache/streampipes/pull/847
- [x] streampipes-model-shared https://github.com/apache/streampipes/pull/847
- [x] streampipes-vocabulary https://github.com/apache/streampipes/pull/869
- [x] streampipes-model https://github.com/apache/streampipes/pull/847
- [x] streampipes-model-client https://github.com/apache/streampipes/pull/847
- [x] streampipes-test-utils https://github.com/apache/streampipes/pull/865
- [x] streampipes-serializers-json https://github.com/apache/streampipes/pull/865
- [x] streampipes-service-discovery-consul https://github.com/apache/streampipes/pull/845
- [x] streampipes-service-discovery https://github.com/apache/streampipes/pull/845
- [x] streampipes-service-base https://github.com/apache/streampipes/pull/845
- [x] streampipes-config https://github.com/apache/streampipes/pull/863
- [x] streampipes-messaging https://github.com/apache/streampipes/pull/827
- [x] streampipes-messaging-kafka https://github.com/apache/streampipes/pull/827
- [x] streampipes-storage-api https://github.com/apache/streampipes/pull/865
- [x] streampipes-storage-couchdb https://github.com/apache/streampipes/pull/865
- [x] streampipes-storage-management https://github.com/apache/streampipes/pull/866
- [x] streampipes-data-explorer https://github.com/apache/streampipes/pull/866
- [x] streampipes-connect-api https://github.com/apache/streampipes/pull/867
- [x] streampipes-dataformat https://github.com/apache/streampipes/pull/864
- [x] streampipes-sdk https://github.com/apache/streampipes/pull/867
- [x] streampipes-rest-shared https://github.com/apache/streampipes/pull/867
- [x] streampipes-container https://github.com/apache/streampipes/pull/867
- [x] streampipes-dataformat-cbor https://github.com/apache/streampipes/pull/864
- [x] streampipes-dataformat-fst https://github.com/apache/streampipes/pull/864
- [x] streampipes-dataformat-json https://github.com/apache/streampipes/pull/864
- [x] streampipes-dataformat-smile https://github.com/apache/streampipes/pull/864
- [x] streampipes-messaging-jms https://github.com/apache/streampipes/pull/827
- [x] streampipes-messaging-mqtt https://github.com/apache/streampipes/pull/827
- [x] streampipes-messaging-nats https://github.com/apache/streampipes/pull/827
- [x] streampipes-security-jwt https://github.com/apache/streampipes/pull/868
- [x] streampipes-user-management  https://github.com/apache/streampipes/pull/869
- [x] streampipes-mail  https://github.com/apache/streampipes/pull/869
- [x] streampipes-resource-management  https://github.com/apache/streampipes/pull/869
- [x] streampipes-measurement-units https://github.com/apache/streampipes/pull/871
- [x] streampipes-pipeline-management https://github.com/apache/streampipes/pull/871
- [x] streampipes-data-export https://github.com/apache/streampipes/pull/871
- [x] streampipes-rest-core-base https://github.com/apache/streampipes/pull/867
- [x] streampipes-connect https://github.com/apache/streampipes/pull/871
- [x] streampipes-connect-container-master https://github.com/apache/streampipes/pull/874
- [x] streampipes-rest https://github.com/apache/streampipes/pull/825
- [x] streampipes-platform-services https://github.com/apache/streampipes/pull/874
- [x] streampipes-backend https://github.com/apache/streampipes/pull/874
- [x] streampipes-client https://github.com/apache/streampipes/pull/874
- [x] streampipes-service-extensions-base https://github.com/apache/streampipes/pull/845
- [x] streampipes-connect-container-worker https://github.com/apache/streampipes/pull/893
- [x] streampipes-container-standalone https://github.com/apache/streampipes/pull/893
- [x] #838
- [x] streampipes-maven-plugin https://github.com/apache/streampipes/pull/893
- [x] streampipes-extensions https://github.com/apache/streampipes/pull/850
- [x] streampipes-pipeline-elements-shared https://github.com/apache/streampipes/pull/850
- [x] streampipes-connect-adapters https://github.com/apache/streampipes/pull/849
- [x] streampipes-connect-adapters-iiot https://github.com/apache/streampipes/pull/849
- [x] streampipes-sdk-bundle https://github.com/apache/streampipes/pull/893
- [x] streampipes-wrapper https://github.com/apache/streampipes/pull/883
- [x] streampipes-wrapper-standalone https://github.com/apache/streampipes/pull/883
- [x] streampipes-processors-filters-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-wrapper-siddhi https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-filters-siddhi https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-transformation-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-sinks-brokers-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-sinks-databases-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-data-explorer-commons https://github.com/apache/streampipes/pull/866
- [x] streampipes-sinks-internal-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-sinks-notifications-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-enricher-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-change-detection-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-extensions-all-iiot https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-image-processing-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-text-mining-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-geo-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-pipeline-elements-all-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-extensions-all-jvm https://github.com/apache/streampipes/pull/850
- [x] streampipes-wrapper-distributed https://github.com/apache/streampipes/pull/883
- [x] streampipes-wrapper-flink https://github.com/apache/streampipes/pull/883
- [x] streampipes-processors-aggregation-flink https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-enricher-flink https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-geo-flink https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-pattern-detection-flink https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-statistics-flink https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-text-mining-flink https://github.com/apache/streampipes/pull/850
- [x] streampipes-processors-transformation-flink https://github.com/apache/streampipes/pull/850
- [x] streampipes-sinks-databases-flink https://github.com/apache/streampipes/pull/850
- [x] streampipes-pipeline-elements-all-flink https://github.com/apache/streampipes/pull/850
- [x] streampipes-pipeline-elements-data-simulator https://github.com/apache/streampipes/pull/850
- [x] streampipes-sources https://github.com/apache/streampipes/pull/893
- [x] streampipes-sources-watertank-simulator https://github.com/apache/streampipes/pull/850
- [x] streampipes-sources-vehicle-simulator https://github.com/apache/streampipes/pull/850
- [x] streampipes-performance-tests https://github.com/apache/streampipes/pull/893
- [x] streampipes-wrapper-kafka-streams https://github.com/apache/streampipes/pull/883
- [x] streampipes-wrapper-python https://github.com/apache/streampipes/pull/883
- [x] integration https://github.com/apache/streampipes/pull/814

Note: The above todo tasks are generated by the command `mvn --also-make dependency:tree | grep maven-dependency-plugin | awk '{ print "- [ ] "$(NF-1) }' `. Please tell me if there are any problems.

### StreamPipes Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by tenthe** [comment]
Hey @RobertIndie,
I'll start with the module `streampipes-rest`.
How can I link the subtask (TODO) to pull requests?

**Comment by RobertIndie** [comment]
Hi @tenthe 
> How can I link the subtask (TODO) to pull requests?

You can edit my Issue description and paste your PR link to the sub-task. And as you are doing now, you can link to this issue in your PR description.

**Comment by tenthe** [comment]
Hi all, I just enabled checkstyle in the module `streampipes-processors-geo-jvm`. 
There we have the case that some files have a different license (MIT). Further, there are other checkstyle `violations` (e.g. an author in comments) that we can't remove.
How can we deal with such cases?

An **example** can be found in package: `org.apache.streampipes.processors.geo.jvm.processor.revgeocoder.geocode.kdtree;`

**Comment by RobertIndie** [comment]
Hi @tenthe Thanks for your comment.
> I just found out that the command mvn validate no longer returns an error when there is a checkstyle problem.

I have created a PR to fix it: https://github.com/apache/streampipes/pull/853

**Comment by RobertIndie** [comment]
Hi, @tenthe 
> There we have the case that some files have a different license (MIT). Further, there are other checkstyle `violations` (e.g. an author in comments) that we can't remove.
How can we deal with such cases?

How about suppressing these files here: https://github.com/apache/streampipes/blob/dev/tools/maven/suppressions.xml
I also found a way to apply different rules to different files: https://stackoverflow.com/questions/25894431/checkstyle-different-rules-for-different-files . But it may introduce some complexity.

**Comment by bossenti** [comment]
Personally, I would prefer option 1 and only suppress the affected rules working with as less wildcards as possible.
The second option can get easily confusing, as fas as I can imagine

**Comment by tenthe** [comment]
Ok, thans to the both of you. I used the first option and added it to PR #850.
This PR should (hopefully) contain all checkstyle fixes for the `streampipes-extension` module
