### ISSUE TITLE
Remove checkboxes from issue templates

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#858]
### Body

If checkboxes are used in issue templates (like this one), they are recognized as tasks by Github.
This is unintentionally and creates some confusion, therefore we should replace checkboxes in our issue templates by dropdown menus.

### Mentoring
As this ticket is marked as good first issue: @bossenti is happy to provide help for getting started, just tag him if you want to start working on this issue and need some help.

### StreamPipes Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by mohitbhagat** [comment]
@bossenti This is my first time contributing to open source, and was wondering if you could help me out. Where can I make the changes to the issue templates? Is this going to require any changes to the source code, or a pull request?

**Comment by bossenti** [comment]
Great that you found your way to StreamPipes 🎉 
If you want to submit a contribution you need to fork the repository and then create a PR from your branch to our repo.
You can find our issue templates here: https://github.com/apache/streampipes/tree/dev/.github/ISSUE_TEMPLATE
Here are some information about GitHubs syntax: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

Feel free to reach out if you have any further questions

**Comment by Ndace-hash** [comment]
@bossenti hello, I would like to work on this issue. 
Is it still an open issue? If yes, do you have any advice on getting started with it?

**Comment by bossenti** [comment]
Hi @Ndace-hash,

great to hear 🎉 
Yes, it is still open, would be great if you could contribute here.

I think from our side there is nothing to add other than the issue description, but if you need any help to get started I'm happy to assist you.
