### ISSUE TITLE
Create PR validation workflow for streampipes-website

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#859]
### Body

Currently, there is no PR validation workflow in place for the `streampipes-website` repository.
As a firs iteration, we could create a workflow that builds both the website and the documentation.
This would help us to evaluate PR more easily and is of great help for dependency updates especially.

### Mentoring
As this ticket is marked as `good first issue`: @bossenti is happy to provide help for getting started, just tag him if you want to start working on this issue and need some help.

### StreamPipes Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by likileads** [comment]
Hi @bossenti, I wish to work on this issue.
Can you please guide me where to get started.

**Comment by likileads** [comment]
Hi @bossenti thanks for helping me out. 
Please review my PR https://github.com/apache/streampipes-website/pull/40
