### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by aamirshaikh7** [apache/streampipes#878]
### Where does your observation occur?

StreamPipes Documentation

### What do you want to report?

README.md subscription mailing list link (line number: 203) redirects to relative path.

![dev subscribe mailing list link](https://user-images.githubusercontent.com/56036364/208986083-8c8a1eba-aac0-48f0-86ec-4d9ecc98c7ea.png)

On clicking "dev-subscribe@streampipes.apache.org" instead of showing "Open Mail" popup, the link redirect to GitHub 404 page not found with message as "The 'apache/streampipes' repository doesn't contain the 'dev-subscribe@streampipes.apache.org' path in 'dev'."

![after clicking on dev subscribe mailing list link](https://user-images.githubusercontent.com/56036364/208986728-937efd47-00f8-46b6-a782-169cf1fe5d83.png)

### Solving the problem

README.md needs to modified, the link format need to be changed to appropriate mailto link i.e: 
\[dev-subscribe@streampipes.apache.org\](mailto:dev-subscribe@streampipes.apache.org)

### Anything left

I'm willing to work on this issue. Can anyone please guide me with how to proceed with the changes. What are the steps that I should follow?. In terms of forking and branch naming conventions. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by bossenti** [comment]
Thanks a lot @aamirshaikh7 for this great bug report 🙏🏼 

It would be really cool if you directly create a PR.
To start you need to fork the `streampipes` repository, like you already assumed.
Create a branch, we don't have strict naming conventions here but it would be awesome if you could include the GitHub id of this issue (#878) in both the branch name and the commit messages.
After that you can simply apply your changes and create a PR, we will then have a look on it.

Looking forward to your contribution!

**Comment by aamirshaikh7** [comment]
Thanks @bossenti 

I have made the changes and opened the PR.
