### ISSUE TITLE
Upgrade to Angular v15

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#943]
### Body

Upgrade to the most recent Angular version (`v15`).
This includes probably some manual code adaptions.
Furthermore, all dependencies related to Angular should also be updated.

### Mentoring
As this ticket is marked as good first issue: @dominikriemer or @tenthe are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue might be a good (but also a bit challenging) issue for people interested in getting familiar with our UI.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by dominikriemer** [comment]
We need to wait until flex-layout has been updated to support Angular 15.
In addition, flex-layout is now deprecated and we need to find a way to replace it from the whole UI:
https://github.com/angular/flex-layout/issues/1430

**Comment by tenthe** [comment]
Hi @TalhaHere12,
as @dominikriemer said above, we need to wait until flex-layout is updated to support Angular 15.
In the meantime, feel free to work on other issues. What would you like to do?
Do you already have experience with Angular?
Cheers,
Philipp

**Comment by TalhaHere12** [comment]
No sir I have worked a little bit on React JS.
sir @tenthe could you please suggest me a beginner friendly issue with React JS.

**Comment by tenthe** [comment]
I'm sorry that we only use Angular for the user interface. There are no React JS components inside StreamPipes.
However, there are also other ways you can contribute (e.g. manually test the software or crate automated test cases with cypress.io).
If you are interested, I would suggest you get familiar with the project and maybe Cypress.
Please let us know if you have any questions.
