### ISSUE TITLE
Example code in docs for Python code is rendered as markdown

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#962]
### Body

We use comments in some examples provided in the pydoc strings, e.g. in the [client base class](https://github.com/apache/streampipes/blob/dev/streampipes-client-python/streampipes_client/client/client.py#L71).
This is recognized by mkdocs as markdown syntax and therefore wrongly formatted as headings.
See the screenshot below:
![wrong-headings](https://user-images.githubusercontent.com/50115603/210132409-1c6998ea-7603-47a8-9297-c0c266bf7bbf.png)

### Mentoring
As this ticket is marked as good first issue: @bossenti  or @kulbachcedric are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue might be a good issue for people interested in the StreamPipes Python client that already have some experience with `Mkdocs`.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by CryoSolace** [comment]
Hello, I would like to try and work on this issue. Are the comments supposed to be displayed on the page at all?

**Comment by bossenti** [comment]
Hi @CryoSolace,

great that you are interested in contributing to StreamPipes 🚀 
Here is one of the examples given in the pydocs:
```python
Examples
--------

>>> from streampipes_client.client import StreamPipesClient
>>> from streampipes_client.client.client_config import StreamPipesClientConfig
>>> from streampipes_client.client.credential_provider import StreamPipesApiKeyCredentials

>>> client_config = StreamPipesClientConfig(
...     credential_provider=StreamPipesApiKeyCredentials(
...         username="test-user",
...         api_key="api-key"
...     ),
...     host_address="localhost",
...     https_disabled=True
... )

>>> client = StreamPipesClient.create(client_config=client_config)

# The above way of instantiating a client instance is intended
# to be consistent with the StreamPipes Java client.
# If you prefer a more pythonic way, you can simply write:
>>> client = StreamPipesClient(client_config=client_config)

# Interact with an endpoint
>>> data_lake_measures = client.dataLakeMeasureApi.all()

# Inspect returned data as a pandas dataframe
>>> data_lake_measures.to_pandas()

    measure_name timestamp_field  ... pipeline_is_running num_event_properties
0           test   s0::timestamp  ...               False                    2
[1 rows x 6 columns]
```
Would be great if the whole code snippet would be rendered correctly in the docs.
Please note our `make` commands for building the docs conventiently: `make doc` and `make livedoc` (see also [here](https://github.com/apache/streampipes/blob/dev/streampipes-client-python/Makefile))
Is there anything else you need to get started?

**Comment by CryoSolace** [comment]
Hi,

Thank you for responding. I would like to know how I can replicate and work
on the issue. I've tried cloning the project but I can't seem to get the
software running or open the docs.

In the mean time, would something like adding # # or \# work?

Thanks.

**Comment by bossenti** [comment]
Alright, so let's assume you have cloned the streampipes repo in a directory called `streampipes`.
Then you can follow this steps:

1. go to `/streampipes/streampipes-client-python`
2. run `pip install ".[docs]"` to install the requirements for the docs ( as far as I know you can leave out the `"` in case you are on windows
3. run `make livedoc` to get the live docs served on `http://127.0.0.1:8000/`
4. In case `make` does not work for you, run the following commands:
```bash
mkdocs build
mkdocs serve --dirtyreload
```
Does that work for you?

Yes, or maybe just leave the `#` out... Feel free to try a few combinations if you want to :) 

PS: I've assigned the ticket to you to indicate that you are on it
Thanks for your interest so far 👍🏼

**Comment by CryoSolace** [comment]
Hi! Thanks for assigning the ticket. I was able to get it working, attached are some ideas. Which one would you rather have in?

![image](https://user-images.githubusercontent.com/100377930/210669308-24158099-e364-492f-822d-1594b58aa452.png)
![image](https://user-images.githubusercontent.com/100377930/210669626-94e27e91-aec0-46e8-a484-f62e40e125a6.png)

**Comment by bossenti** [comment]
I like the second one more, but how about you? 
Which one would you prefer? Or would you make something completely different.
I'm happy to here your thoughts

**Comment by CryoSolace** [comment]
I agree. I think it feels more like documentation and less like comments in the code. I have made a [pull request](https://github.com/apache/streampipes/pull/1059) for this. Let me know if I've made any mistakes or if you want to change anything. Thanks for letting me contribute.
