### ISSUE TITLE
Display inherited methods and their docstrings as well in Mkdocs

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#963]
### Body

With the current setup, inherited methods and their docstrings are unfortunately not displayed in the references of our Python client documentation. This should be the case since we use inheritance a lot here and want to provide the information at the right and intuitive place.

### Mentoring
As this ticket is marked as good first issue: @bossenti is happy to provide help for getting started, just tag him if you want to start working on this issue and need some help.
This issue might be a good issue for people who are interested in StreamPipes' Python client and already have some experience with `Mkdocs`.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by ittuann** [comment]
I would like to contribute! Could you please assign it to me? @bossenti
